chnsz/golangsdk

openstack/fgs/v2/trigger/requests.go
The 'EventTypeCode' json behavior of trigger createOpts should be omitempty, not required.
**Which issue this PR fixes**:
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
```
NONE
```
```release-note
1. replace type code behavior with 'omitempty'.
```
```
NONE
```
=> fix(fgs/trigger): update param behavior for structure

openstack/obs/conf.go
ProxyFromEnvironment returns the URL of the proxy to use for a
given request, as indicated by the environment variables
HTTP_PROXY, HTTPS_PROXY and NO_PROXY (or the lowercase versions
thereof). HTTPS_PROXY takes precedence over HTTP_PROXY for https
requests.
```release-note
```
=> fix: get the proxy URL from environment variables in obs client

openstack/cce/v1/persistentvolumeclaims/requests.go, openstack/cce/v1/persistentvolumeclaims/results.go, openstack/cce/v1/persistentvolumeclaims/urls.go
Add new pvc sdk support
- Create: create a new pvc by importing EVS disk, OBS bucket or SFS file system.
- List: get pvc list by cluster ID and namespace.
- Delete: delete specifies pvc form CCE namespace by cluster ID, namespace and pvc name.
```release-note
1. add new CCE pvc sdk support.
```
=> feat(cce/pvc): add new pvc sdk for cce service

openstack/dli/v1/databases/requests.go, openstack/dli/v1/databases/results.go, openstack/dli/v1/databases/testing/fixtures.go, openstack/dli/v1/databases/testing/requests_test.go, openstack/dli/v1/databases/urls.go
For DLI service, add a new SQL database sdk support:
- Create a new database
- Obtain a database list
- Update database owner
- Delete database
```
NONE
```
```release-note
1. add new database sdk support.
```
```
go test -v -run Test
=== RUN   TestCreateV1Database
--- PASS: TestCreateV1Database (0.00s)
=== RUN   TestListV1Database
--- PASS: TestListV1Database (0.00s)
=== RUN   TestUpdateV1DatabaseOwner
--- PASS: TestUpdateV1DatabaseOwner (0.00s)
=== RUN   TestDeleteV1Database
--- PASS: TestDeleteV1Database (0.00s)
PASS
ok      github.com/chnsz/golangsdk/openstack/dli/v1/databases/testing   0.015s
```
=> feat(dli/sql database): add new database sdk support

openstack/dli/v2/batches/requests.go, openstack/dli/v2/batches/testing/fixtures.go
Due to the problem of API design, the field of `ClassName` is required for `jars`, `pythons`, and `user files`.
In fact, the two types of `pythons` and `user files` can be left blank, but the API requires that the value must be passed (empty string).
So, the type of `ClassName` must be changed to the optional pointer.
```
NONE
```
```release-note
1. update the type of class name from string to the optional pointer.
```
=> fix(arg/type): update the type of class name from string to pointer

openstack/dli/v1/flinkjob/results.go
Because the documentation does not match the actual return of api, so temporarily add three fileds from job to config.
=> fix(DLI): add three fileds from job to config

openstack/cci/v1/namespaces/requests.go, openstack/cci/v1/namespaces/results.go
For some parameters, their type is bool, but the API requires them to enter a string value and return the same type.
In this case, we can use json automatic parsing instead of manual type conversion.
```
NONE
```
```release-note
1. Update the json tag of the parameter for boolean string type.
```
=> refactor(cci/namespace): update json tag of bool string

openstack/cci/v1/namespaces/requests.go, openstack/cci/v1/namespaces/results.go
For some parameters, their type is integer, but the API requires them to enter a string value and return the same type.
In this case, we can use json automatic parsing instead of manual type conversion.
refer to #54 
```
NONE
```
```release-note
1. Update the json tag of the parameter for integer string type.
```
=> refactor(cci/namespace): update json tag of integer string

openstack/cbr/v3/vaults/requests.go
The type of `Limit` and `Offset` parameters of the ListOpts are wrong.
```
NONE
```
```release-note
1. update the parameter types.
```
=> fix(cbr/vaults): update parameter types of the listopts

openstack/cci/v1/networks/requests.go
The json tag of the CIDR argument is wrong, should be `cidr` string.
The CIDR is an abbreviation of proper nouns, should be `CIDR`, not `Cidr`.
`NONE`
```release-note
1. update the json tag of the CIDR.
2. update the argument name's format of the CIDR.
```
=> fix: style: update the cidr of the specification

openstack/cci/v1/networks/requests.go
Fix the json tag of subnet ID of CCI network request structure.
- from `required` to `optional`
```
NONE
```
```release-note
1. update the json tag of subnet ID.
```
=> fix: readjust json tag of subnet id

openstack/cci/v1/networks/requests.go
The json tag of the CIDR argument is wrong, should be `cidr` string.
`NONE`
```release-note
1. fix the wrong json tag of the CIDR.
```
=> fix(cci/network): update the cidr of the specification

openstack/evs/v2/cloudvolumes/requests.go, openstack/evs/v2/cloudvolumes/results.go
- The parameter type of request metadata is wrong.
- The response metadata is incomplete.
- The request structure is missing some parameters, such as:
- `IDs`
- `AvailabilityZone`
- `DedicatedStorageID`
- `DedicatedStorageName`
- `EnterpriseProjectID`
- `Multiattach`
- `ServiceType`
- `VolumeTypeID`
- The request structure is missing some parameters, such as:
- `Links`
- `OsVolTenantAttrTenantID`
- `ServiceType`
- `DedicatedStorageID`
- `DedicatedStorageName`
```
NONE
```
```release-note
1. Add some parameters to request and response structures of list method.
2. update parameter type of request metadata from map to string according to the documentation.
3. update …
```
=> refactor(evs/volume): update structures of list method

openstack/dms/v1/topics/doc.go, openstack/dms/v1/topics/requests.go, openstack/dms/v1/topics/results.go, openstack/dms/v1/topics/urls.go
Package topics is only used by terraform-provider-flexibleengine with
DmsV1Client to manage flexibleengine_dms_kafka_topic resource.
```release-note
```
=> feat: add dms kafka topics v1 APIs for orange

openstack/apigw/shared/v1/environments/requests.go, openstack/apigw/shared/v1/environments/results.go, openstack/apigw/shared/v1/environments/urls.go
To support shared APIG creation for FunctionGraph trigger, the environment related method `List` is needed.
```release-note
1. Add list method to obtain environments of shared APIG.
```
=> feat(apig/shared): add new environment sdk support

openstack/networking/v3/security/groups/requests.go, openstack/networking/v3/security/groups/results.go, openstack/networking/v3/security/groups/urls.go, openstack/networking/v3/security/rules/requests.go, openstack/networking/v3/security/rules/results.go, openstack/networking/v3/security/rules/urls.go
The OpenStack Nova API does not support EPS permission, need to use the v3 sdk to fix it.
```release-note
1. support v3 sdks of security groups and rules.
```
=> feat(secgroup): add v3 sdk support for security groups and rules

openstack/elb/v2/listeners/results.go, openstack/elb/v2/loadbalancers/results.go, openstack/elb/v2/loadbalancers/testing/fixtures.go, openstack/elb/v2/monitors/requests.go, openstack/elb/v2/pools/results.go
A new argument `Type` is added to UpdateOpts in #100 . But it is mistakenly set to required.
This need to be fixed.
```release-note
fix arg 'type' in UpdateOpts to omitempty
```
Testing result:
```
go test ./openstack/elb/v2/loadbalancers/testing -v -run Test
=== RUN   TestListLoadbalancers
--- PASS: TestListLoadbalancers (0.01s)
=== RUN   TestListAllLoadbalancers
--- PASS: TestListAllLoadbalancers (0.00s)
=== RUN   TestCreateLoadbalancer
--- PASS: TestCreateLoadbalancer (0.01s)
=== RUN   TestRequiredCreateOpts
--- PASS: …
```
=> fix(lb/monitors): fix arg 'Type' in UpdateOpts to omitempty

openstack/networking/v3/security/groups/requests.go
For about EPS authorization, the list mothod cannot obtain security groups without the value of the `enterprise_project_id` as `all_granted_eps`.
```release-note
1. Add 'all_granted_eps' as the enterprise project ID in listOpts.
```
=> feat(eps): list method support eps authorization

openstack/cloudtable/v2/clusters/requests.go, openstack/cloudtable/v2/clusters/results.go, openstack/cloudtable/v2/clusters/urls.go
The v2 API of the CloudTable cluster has been released. To support the development of `huaweicloud_cloudtable_cluster`, the new SDK needs to be supported.
```release-note
1. add new cluster sdk support of the CloudTable cluster.
```
=> feat(cloudtable/cluster): add new cluster sdk support

openstack/evs/v2/cloudvolumes/requests.go, openstack/evs/v2/cloudvolumes/results.go
According to the recently updated interface design, marker pages should be used as the pagination page for list query.
```release-note
1. Use marker pages instead of linked pages.
```
=> fix(volume/list): use marker pages instead of linked pages

openstack/evs/v2/cloudvolumes/requests.go
The old charging mode structure is no longer applicable to the v2 creation API of the EVS volume.
```release-note
1. update charging mode structure.
```
=> feat(evs/volume): update params of the charging infomation

openstack/evs/v2/cloudvolumes/requests.go
The `ExtendSize()` method lacks the API response, and its auto-pay parameter does not work properly.
```release-note
1. fix the problem that the return body is missing.
2. fix the wrong tag name of parameter auto-pay.
```
=> fix(evs/volume): fix the problem that the resize method cannot be used

openstack/elb/v2/listeners/requests.go, openstack/elb/v2/loadbalancers/requests.go, openstack/elb/v3/listeners/requests.go
change type of Description to pointer in UpdateOpts, then we can update this field to null.
```release-note
```
=> fix(elb): change type of Description to pointer in UpdateOpts

openstack/cci/v1/networks/requests.go
Since the query interfaces of the CCI namespace does not return relevant information about the network, it is necessary to provide a List method to query the network information of the current namespace.
```release-note
1. add list method to obtain namespace networks.
```
=> feat(cci/network): add list method to obtain namespace networks

openstack/cce/v3/clusters/results.go
add parameter ClusterTags in CreateOpts
```release-note
add parameter ClusterTags in CreateOpts
```
**Test results**:
```
go test ./openstack/cce/v3/clusters/testing -v -run Test
=== RUN   TestGetV3Cluster
--- PASS: TestGetV3Cluster (0.00s)
=== RUN   TestGetV3ClusterOTC
--- PASS: TestGetV3ClusterOTC (0.00s)
=== RUN   TestListV3Cluster
--- PASS: TestListV3Cluster (0.00s)
=== RUN   TestListV3ClusterOTC
--- PASS: TestListV3ClusterOTC (0.00s)
=== RUN   TestCreateV3Cluster
--- PASS: TestCreateV3Cluster (0.01s)
=== RUN   TestUpdateV3Cluster …
```
=> feat(cce/cluster): add parameter ClusterTags in CreateOpts

openstack/csbs/v1/backup/results.go, openstack/csbs/v1/backup/testing/requests_test.go
when unmarshal  the API response of GET method, an error is arising:
```
json: cannot unmarshal number 28.1 into Go struct field .checkpoint_item of type int
```
the API Response Body is as follows:
```
{
"checkpoint_item": {
"extend_info": {
"average_speed": 28.1,
"volume_backups": [
{
"average_speed": 0,
}
]
},
}
}
```
actually, we doesn't use the **average_speed** item, so we can not unmarshal it as the response maybe changed.
```release-note
```
=> fix(csbs): do not unmarshal average_speed item

openstack/networking/v1/security/rules/requests.go, openstack/networking/v1/security/rules/results.go, openstack/networking/v1/security/rules/urls.go
Due to ver.3 APIs of Security Group Rule are not supported in some regions, like `ap-southeast-2`. So, we need to support an older version (ver.3) of the API.
```release-note
1. add new ver.1 sdk support.
```
=> feat(secgroup/rule): add new ver.1 sdk support

openstack/apigw/dedicated/v2/apis/urls.go, openstack/apigw/dedicated/v2/channels/urls.go, openstack/apigw/dedicated/v2/responses/requests.go, openstack/apigw/dedicated/v2/responses/urls.go, openstack/apigw/dedicated/v2/throttles/urls.go, openstack/dms/v1/groups/requests.go, openstack/dms/v1/groups/urls.go, openstack/dms/v1/queues/requests.go, openstack/dms/v1/queues/urls.go, openstack/mrs/v2/jobs/urls.go, openstack/networking/v2/extensions/elbaas/backendmember/requests.go, openstack/networking/v2/extensions/elbaas/backendmember/urls.go, openstack/rds/v1/flavors/requests.go, openstack/rds/v1/flavors/urls.go, openstack/taurusdb/v3/instances/results_job.go, openstack/taurusdb/v3/instances/urls.go
There are some non-standard usages in urls.go files, which make it impossible to parse right API url
1.  use client.ServiceURL(...)  to replace the functions which use fmt.sprintf to build URL path.
2.  the functions arguments which have query params, remove params to requests.go.
```release-note
```
=> chore: remove some non-standard usages in urls.go

openstack/networking/v1/security/rules/requests.go
The port range parameters are missing omitempty behavior.
```release-note
1. fix port null value exception.
```
=> fix(secgroup/rule): fix port null value exception

openstack/compute/v2/extensions/floatingips/urls.go, openstack/dcs/v1/availablezones/urls.go, openstack/dcs/v1/instances/urls.go, openstack/dcs/v1/maintainwindows/urls.go, openstack/dcs/v1/products/urls.go, openstack/dcs/v2/availablezones/urls.go, openstack/dcs/v2/flavors/urls.go, openstack/dcs/v2/instances/urls.go, openstack/dcs/v2/maintainwindows/urls.go, openstack/dcs/v2/tags/urls.go, openstack/dcs/v2/whitelists/urls.go, openstack/dms/v1/availablezones/urls.go, openstack/dms/v1/groups/urls.go, openstack/dms/v1/instances/urls.go, openstack/dms/v1/maintainwindows/urls.go, openstack/dms/v1/products/requests.go, openstack/dms/v1/products/urls.go, openstack/dms/v1/queues/urls.go, openstack/dms/v1/topics/urls.go, openstack/dms/v2/availablezones/urls.go, openstack/dms/v2/kafka/instances/urls.go, openstack/dms/v2/kafka/topics/urls.go, openstack/dms/v2/maintainwindows/urls.go, openstack/dms/v2/products/urls.go, openstack/dms/v2/rabbitmq/instances/urls.go
There are some non-standard usages in urls.go files, which makes it impossible to parse the right API URL.
1. config dcs,dms client without projectID in provider, so remove strings.replace from urls.go, and add projectId to some func
```release-note
```
=> chore: remove strings.replace in urls.go

openstack/servicestage/v2/applications/requests.go, openstack/servicestage/v2/applications/results.go, openstack/servicestage/v2/applications/urls.go
Add new application sdk for the ServiceStage Service:
- support CRUD methods for application.
- support configurations of the environment variables.
```release-note
1. add new servicestage sdk support.
```
=> feat(servicestage): Add new application sdk support for ServiceStage Service

openstack/apigw/dedicated/v2/instances/results.go
The response of `UpdateEgressBandwidth()` method is a string, to interpret it, we support a `Extract()` method to handle it.
But this method is not available for the response body of the `EnableEgressAccess()` method.
```
Unable to parse JSON: json: cannot unmarshal string into Go value of type map[string]interface {}
```
```release-note
1. add a new method to interpret structure and rename the old one.
```
=> fix(apig/egress): rename extract method and support a new one

openstack/apigw/dedicated/v2/instances/results.go
Since the return Body of the Post method and the Put method are different, the result should be separated.
The response of `UpdateEgressBandwidth()` method is a string, to interpret it, we support a `Extract()` method to handle it.
But this method is not available for the response body of the `EnableEgressAccess()` method.
```
Unable to parse JSON: json: cannot unmarshal string into Go value of type map[string]interface {}
```
```release-note
1. separate two 'Extract()' methods.
2. add assertion failure handling logic in 'Extract()' …
```
=> fix(apig/egress): fix the assertion failure panic

openstack/cbr/v3/vaults/results.go
Add new structure and function to extract vault orders.
The API response of prepaid order is:
```
{
"errText": "success",
"error_code": "0",
"orders": [
{
"cloudServiceId": null,
"orderId": "CS2206061640RCV6T",
"reserveInstanceIds": [],
"resourceId": "377538e1-7684-4705-9745-d8f4bc60a9c3",
"subscribeResult": null
}
],
"retCode": 0
}
```
```release-note
1. add new structure and function to extract vault orders.
```
=> feat(cbr/vault): add new function to extract vault orders

openstack/ecs/v1/block_devices/results.go
When we get the volume under the specified instance, if the volume has been deleted, an error occurs.
```
{
"error": {
"code": "Ecs.1000",
"message": "{\"itemNotFound\": {\"message\": \"No volume Block Device Mapping with id bf70bd77-38dd-4db3-b473-31db1afc4733.\", \"code\": 404}}"
}
}
```
Now we support a structure to parsing it.
```release-note
1. support an error structure.
```
=> feat(evs/attach): add an error structure

openstack/fgs/v2/trigger/results.go
When we get the trigger under the specified function, if the function or trigger has been deleted, an error occurs.
```
Error: error retrieving FunctionGraph trigger: Internal Server Error: [GET https://functiongraph.cn-north-4.myhuaweicloud.com/v2/0970dd7a1300f5672ff2c003c60ae115/fgs/triggers/urn:fss:cn-north-4:0970dd7a1300f5672ff2c003c60ae115:function:default:script_fgs_triggers_function], error message: {
│  "error_code": "FSS.0500",
│  "error_msg": "Error getting associated function"
│ }
```
Now we support a error structure and parse it.
**Release …
=> feat(fgs/trigger): add an error structure

openstack/servicestage/v2/instances/requests.go
According to the current structure using, the configuration structure must be provided even it is empty. Otherwise, the component will fail to be deployed.
```release-note
1. replace structure pointer with normal structure.
```
=> fix(configuration): allow empty structure when body building

openstack/servicestage/v2/instances/results.go
- The `omitempty` tag is unnecessary if the structure is using for API response.
- Now we have a new parameter `internal` to mark whether variable is system variable.
```release-note
1. remove the omitempty tag from response structure
2. support a new env structure
```
=> feat: fix(env/variable): update response structures

openstack/meeting/v1/conferences/requests.go, openstack/meeting/v1/conferences/urls.go
Provides a way to query conferences without using conference UUID.
```release-note
1. add histories list method.
```
=> feat(meeting/conference): add histories list method

openstack/servicestage/v2/jobs/requests.go, openstack/servicestage/v2/jobs/results.go
The `Get` method can only query a maximum of 20 records for deployment task, that is, the content of one page and not satisfied with the existing scenario.
```release-note
```
=> feat(servicestage/job): support a list method and deprecate get method

openstack/dms/v2/kafka/instances/requests.go, openstack/dms/v2/kafka/instances/results.go, openstack/dms/v2/products/requests.go, openstack/dms/v2/products/results.go, openstack/dms/v2/products/urls.go
- Support a new method to query products of the new format. (the old format is `00300-30308-0--0`, the new format is `c6.2u4g.cluster`).
- Add and update some parameters to support the creation of kafka instances with new format products.
- **specification**: required -> optional
- **partition_num**: required -> optional
- new parameter **broker_num** and the behavior is optional
```release-note
1. support a new method to query the new products for the new format.
2. add and update some parameters to support the creation of kafka …
```
=> feat(dms/product): add new query method support

openstack/evs/v2/cloudvolumes/requests.go, openstack/evs/v2/snapshots/requests.go, openstack/evs/v2/snapshots/results.go
In the k8s csi integration, paging data must be specified when querying the list, so add functions for querying the list of EVS volumes and snapshots.
```release-note
```
=> feat(evs): add functions for EVS volume and snapshots

openstack/networking/v3/security/groups/requests.go, openstack/networking/v3/security/groups/results.go, openstack/networking/v3/security/rules/requests.go, openstack/networking/v3/security/rules/results.go
The parameter type of priority should be integer, but string.
```release-note
1. update the incorrect parameter type from string to int.
```
=> fix(secgroup): fix the incorrect parameter type for priority

openstack/dds/v3/instances/requests.go, openstack/dds/v3/instances/results.go, openstack/dds/v3/instances/urls.go, openstack/dds/v3/jobs/requests.go, openstack/dds/v3/jobs/results.go, openstack/dds/v3/jobs/urls.go
The API has been support the port parameter for create and update method, but we were not supported.
To query the progress of the databse access port modifying, we need to add a job sdk.
```release-note
1. add job sdk and support modify method for port.
```
=> feat(dds/instance): add job sdk and support modify method for port

openstack/identity/v3/roles/requests.go, openstack/identity/v3/roles/results.go, openstack/identity/v3/roles/testing/fixtures.go, openstack/identity/v3/roles/testing/requests_test.go
The List method can only return a single page without 'page' and 'per_page' parameters.
```release-note
1. fix the bug that List method can only return a single page.
```
=> fix(iam/roles): fix the bug that List method can only return a single page

openstack/dds/v3/instances/results.go
The API response of the Create method is missing `order_id`, and the update method has not Extract method.
```release-note
1. add new parameter order_id into reponse structure of Create method.
2. support response structure and extract method for update method.
```
=> feat(dds/instance): support prepaid and update response

.gitignore, openstack/networking/v1/subnets/requests.go, openstack/networking/v1/subnets/testing/requests_test.go, openstack/networking/v1/vpcs/requests.go, openstack/networking/v1/vpcs/testing/requests_test.go
Adds Tags request parameters to V1 VPC and subnet list requests.
fixes #236 
Expect similar PRs for other resources in the (near) future.
```release-note
```
=> Networking resources tag filters

openstack/er/v3/associations/requests.go, openstack/er/v3/associations/results.go, openstack/er/v3/associations/urls.go, openstack/er/v3/propagations/requests.go, openstack/er/v3/propagations/results.go, openstack/er/v3/propagations/urls.go, openstack/er/v3/routes/requests.go, openstack/er/v3/routes/results.go, openstack/er/v3/routes/utls.go, openstack/er/v3/routetables/requests.go, openstack/er/v3/routetables/results.go, openstack/er/v3/routetables/urls.go
In order to support the route table resource, four kinds of ER sdks are needed.
- route table
- route
- association
- propagation
The relationship of them are as follows:
```
- ER instance
|- attachment
|- route table
|- route
|- association
|- propagation
```
```release-note
1. support route table sdk.
2. support route sdk.
3. support association sdk.
4. support propagation sdk.
```
=> feat(er): Four sdks are supported for ER service

openstack/nat/v2/gateways/requests.go, openstack/nat/v2/gateways/results.go, openstack/nat/v2/gateways/urls.go
Support new ver.2 gateway sdk
The differences between new sdk (/openstack/nat/v2/gateways) and old sdk (/openstack/networking/v2/natgateways) are as follows:
- New sdk delete the parameter `tenant_id` from the request body.
- New sdk add a new parameter `created_at` to the response body.
```release-note
1. add new gateway sdk support.
```
=> feat(nat/gateway): support new ver.2 gateway sdk

openstack/cce/v3/clusters/results.go
CCE Turbo supports the creation of distributed clusters, and it can manage remote clusters or nodes.
And the v3 API of CCE has opened the creation parameter of this function: `"enableDistMgt"`
If we enable the parameter: `"enableDistMgt"`, we can create a distributed CCE Turbo cluster：
```release-note
```
=> feat(cce/turbo): support enable distributed CCE-Turbo cluster Management

openstack/cce/v3/nodes/results.go, openstack/cce/v3/partitions/doc.go, openstack/cce/v3/partitions/requests.go, openstack/cce/v3/partitions/results.go, openstack/cce/v3/partitions/testing/doc.go, openstack/cce/v3/partitions/testing/fixture.go, openstack/cce/v3/partitions/testing/requests_test.go, openstack/cce/v3/partitions/urls.go
Related to PR: https://github.com/huaweicloud/terraform-provider-huaweicloud/pull/2956
The partitions is a new feature introduced by CCE Turbo remote distributed cluster management. Currently, partitions are divided into three categories: Center, HomeZone, and IES.
- `Default`: Indicates the availability zone resources of the HuaweiCloud data center.
- `HomeZone`: Indicates the edge computing area in the user's home, which is not currently supported.
- `IES`: IES is the edge station of HuaweiCloud, which deploys user-specific cloud resources to the local computer zone.
The concept of partitions can support CCE Turbo to manage distributed nodes, which has strong applicability in the field of edge computing.
1. When we create a CCE Turbo and enable …
=> feat(cce/turbo): support CCE Turbo partition management

openstack/modelarts/v1/notebook/results.go
The offset query parameter is a parameter used to calculate the page number, not the real offset. Therefore, the traditional offset calculation is no longer applicable to the notebook images of the ModelArts service.
- In traditional offset calculation, the offset of next page URL is `offset + limit`, and the query result is as follow:
(Assuming that the total number of images is 33, the limit adopts the default value)
```
The first querying result: limit=200, offset=0
{
current: 0,
data: [...], // the length of data array is 33.
pages: 1,
size: 200, // the maximum number for a page.
total: 33
}
The second querying result: limit=200, offset=233
{
"error_code": "ModelArts.6400",
"error_msg": "fromIndex(200) \u003e toIndex(33)"
}
```
- In new offset …
=> fix(modelarts/notebook): fix the next page calculation of URL

openstack/mrs/v2/clusters/requests.go
1. Add vpc_id to CreateOps. There is a bug in this API, when adding an external data source, vpc_id is required.
2. Remove useless parameters from ExternalDatasource struct
```release-note
```
=> feat(MRS): add vpc_id to CreateOps

openstack/dns/v2/nameservers/requests.go, openstack/dns/v2/nameservers/results.go, openstack/dns/v2/nameservers/urls.go
the API URL: https://support.huaweicloud.com/intl/en-us/api-dns/dns_api_69001.html
```release-note
```
=> feat: support to query DNS nameservers

openstack/waf_hw/v1/policies/requests.go, openstack/waf_hw/v1/policies/results.go
- Policy add new fields: robot_action, bind_hosts, deep_inspection, header_inspection, shiro_decryption_check, options.geolocation_access_control, options.information_leakage_prevention, options.bot_enable, options.known_attack_source, options.anti_crawler
- Make options fields Optional.
- Remove BindHost omitempty mark。
- The update parameters is use less: modulex_options, hosts, bind_host, extend
API URL： https://support.huaweicloud.com/api-waf/UpdatePolicy.html
```release-note
```
=> feat: WAF policy add new fields

openstack/apigw/dedicated/v2/apis/requests.go, openstack/apigw/dedicated/v2/apis/results.go
Wrong type of parameter passthrough, should be `integer`, but got `string`.
```release-note
1. update the type of parameter passthrough.
```
=> feat: fix(apig/api): support some parameter and update parameter type

openstack/apigw/dedicated/v2/throttles/results.go
Invalid parameter name.
wrong name: is_include_special_throttle
right name: is_inclu_special_throttle
```release-note
1. update the parameter name from 'is_include_special_throttle' to 'is_inclu_special_throttle'.
```
=> fix(apig/throttle): wrong response parameter name

openstack/apigw/dedicated/v2/instances/requests.go, openstack/apigw/dedicated/v2/instances/results.go, openstack/apigw/dedicated/v2/instances/urls.go
The latest API support some new parameters:
+ bandwidth_charging_mode
+ tags (just support, maybe not use)
+ vpcep_service_name
+ ingress_bandwidth_size
+ ingress_bandwidth_charging_mode
And support some response parameters.
For tags management, support two functions:
+ UpdateTags()
+ GetTags()
```release-note
1. support some parameters.
2. support tags operate functions.
```
=> feat(apig/instance): support some parameters and functions

openstack/cbr/v3/vaults/requests.go
The consistent level can be updated.
But only `crash_consistent` can be udpated to `app_consistent`, the `app_consistent` cannot be udpated to `crash_consistent`.
```release-note
1. add consistent level to the 'BillingUpdate' structure.
```
=> feat(cbr/vault): consistent level can be updated

openstack/eps/v1/enterpriseprojects/requests.go, openstack/eps/v1/enterpriseprojects/results.go
Update the structure name and append a new parameter: target enterprise project ID.
NOTE: The structure and the corresponding function are never used.
```release-note
1. rename the structure and corresponding function.
2. update the list method logic and return parameters.
```
**Searching results**:
=> chore(eps): rename and update the list method

openstack/waf_hw/v1/premium_domains/requests.go, openstack/waf_hw/v1/premium_domains/results.go
fix WAF dedicated domain struct fields
- The API link refer to: https://support.huaweicloud.com/api-waf/CreatePremiumHost.html
- For update request body, `locked`, `protect_status`, `access_status`, `timestamp`, `pool_ids` is useless. And `web_tag` is not stated in the documentation, but it is actually available.
```release-note
```
=> fix(WAF): fix WAF dedicated domain struct fields

openstack/cbr/v3/members/requests.go, openstack/cbr/v3/members/results.go, openstack/cbr/v3/members/urls.go
Support a new sdk to share backup (manage backup shared members).
These methods are supported:
- Create
- List
- Delete
```release-note
1. add new sdk support for CBR service to share backup.
```
=> feat(cbr/backup): support a new sdk to share backup

openstack/workspace/v2/accesspolicies/requests.go
Invalid json name for object list parameter, want 'policy_objects_list', but got 'policy_object_list'.
```release-note
1. update json name for policy object list parameter in create opts.
```
=> fix(workspace): invalid json name for object list

openstack/cbr/v3/members/requests.go
Support new method to update backup share status
```release-note
1. support a new method to update the shared member or shared backup status.
```
=> feat(cbr/backup): Support new method to update backup share status

openstack/fgs/v2/function/results.go
The parameter `depend_list` has been deprecated and the parameter `depend_version_list` is used instead.
Currently, all new dependency packages are dependency packages with versions. 
- However, old dependency packages without versions will be automatically processed as dependency packages with versions by the service. This problem occurs only when they are used for the first time.
```release-note
1. Mark the parameter `depend_list` with the `deprecated` comment.
2. Support a new parameter `depend_version_list`.
```
=> chore(fgs/function): support a new param: depend_version_list

openstack/antiddos/v2/alarmreminding/requests.go, openstack/antiddos/v2/alarmreminding/results.go, openstack/antiddos/v2/alarmreminding/testing/requests_test.go, openstack/antiddos/v2/alarmreminding/urls.go
It is confirmed that the following parameters in the interface are discarded:
back_doors、bruce_force、high_privilege、remote_login、send_frequency、waf、weak_password
go test -v ./
=== RUN   TestQueryTraffic
--- PASS: TestQueryTraffic (0.01s)
PASS
ok      github.com/chnsz/golangsdk/openstack/antiddos/v2/alarmreminding/testing 0.016s
=> feat(Anti-DDoS): antiddos resource support alarm configuration

openstack/networking/v1/bandwidths/results.go, openstack/networking/v2/bandwidths/requests.go
Add params `bandwidth_type` and `public_border_group` for resource `huaweicloud_vpc_bandwidth`.
=> chore(eip): add params for resource vpc bandwidth

openstack/workspace/v2/services/requests.go, openstack/workspace/v2/services/results.go, openstack/workspace/v2/services/urls.go
Provide the capability of activating Workspace services that have not been used for 14 days.
```release-note
1. The Workspace service can be unlocked.
```
=> feat(workspace): the service support unlock action

openstack/bms/v1/baremetalservers/requests.go, openstack/bms/v1/baremetalservers/urls.go
bms instance support manage server status
```release-note
1.BMS server supports three operations to manage server status：start, stop and reboot.
2.The type field in the structure body supports HARD and SOFT. Only HARD takes effect.
```
=> feat(BMS): bms instance support manage server status

openstack/cce/v3/nodes/results.go
This change is necessary in order to merge this PR https://github.com/huaweicloud/terraform-provider-huaweicloud/pull/3906
The change affects the structure of taints, which allows you to leave "Value" empty
=> fix: omitempty for taint spec field "Value"

openstack/fgs/v2/application/requests.go, openstack/fgs/v2/application/results.go, openstack/fgs/v2/application/urls.go
DataSource: huaweicloud_fgs_application_templates.
The data source supports getting list of application templates.
```release-note
1. Use this data source to get the list of application templates.
```
=> feat(fgs): the datasource supports getting list of application templates

openstack/apigw/dedicated/v2/apigroups/requests.go, openstack/apigw/dedicated/v2/apigroups/results.go, openstack/apigw/dedicated/v2/apigroups/urls.go
Support for associating domain names with  API group.
```release-note
1.  up to five domain names can be associate to each API group.
```
=> feat(apig): support binding domain names for specified API groups

openstack/csms/v1/secrets/requests.go, openstack/csms/v1/secrets/results.go
csms secret resource support secret_binary and expire_time parameter
```release-note
Csms support expire_time when update secret versions. 
```
=> feat(csms): csms secret resource support expire_time parameter

openstack/drs/v3/jobs/requests.go, openstack/drs/v3/jobs/results.go, openstack/drs/v3/jobs/urls.go
Support dual-AZ in `hauweicloud_drs_job` and fix the tyoe of attribute `node_num`
The API docs: https://support.huaweicloud.com/intl/en-us/api-drs/drs_03_0106.html
`region\projectId\instid\vpcId\subnetId` is not in docs but required in actual
=> feat(drs): support dual AZ in job

openstack/elb/v3/pools/requests.go, openstack/elb/v3/pools/results.go
Support new params for `huaweicloud_elb_pool`, including `ip_version` and `member_deletion_protection_enable`.
=> feat(elb): support new params for pool

openstack/dli/v3/elasticresourcepool/requests.go, openstack/dli/v3/elasticresourcepool/results.go, openstack/dli/v3/elasticresourcepool/urls.go
The resource supports configuring the queue scaling policy to the specified elastic resource pool.
the API document states that the default value of limit is 100, but if offset is specified without limit,
paging will not take effect.
```release-note
```
=> feat(dli): support queue scaling policies to an elastic resource pool

openstack/dli/v1/flinkjob/requests.go, openstack/dli/v1/flinkjob/results.go, openstack/dli/v3/flinkjob/requests.go, openstack/dli/v3/flinkjob/result.go, openstack/dli/v3/flinkjob/urls.go
1. The flink sql job supports generating stream graphs.
2. The flink sql job supports `flink_version` parameter.
```release-note
1. add a API that is used to generate a static stream graph or simplified stream graph  for a Flink SQL job.
2. the UpdateSqlJobOpts.OperatorConfig and UpdateSqlJobOpts.StaticEstimatorConfig parameters can be set to empty string.
```
=> feat(dli): the flink sql job supports generating stream graphs

openstack/elb/v2/pools/requests.go, openstack/elb/v2/pools/results.go
Support new params for shared pool, including `protection_status` and `protection_reason`.
=> feat(elb): support new params for shared pool

openstack/apigw/dedicated/v2/authorizers/requests.go, openstack/apigw/dedicated/v2/authorizers/results.go
Supports some function-related parameters for APIG custom authorizer.
- network_type
- authorizer_version
- authorizer_alias_uri
```release-note
1. new parameters supported for custom authorizer.
```
=> feat(apig): new parameters supported for custom authorizer

openstack/dms/v2/kafka/instances/requests.go
Support new param arch type for kafka instance, and this param is not in return.
=> feat(dms): support new param arch type for kafka instance

openstack/modelarts/v1/notebook/requests.go, openstack/modelarts/v1/notebook/results.go
The EFS turbo creation needs the volume.id parameter and it is a required param for the dedicated notebook
```release-note
support new params for volume strcuture
```
=> feat(modelarts/notebook): support new params for volume strcuture

openstack/waf_hw/v1/premium_instances/requests.go
WAF dedicated sdk support new field.
- Change `cpu_flavor` from required to omitempty.
- Add new field `anti_affinity`. This field does not have response value.
```release-note
```
=> feat(WAF): WAF dedicated sdk support new field

openstack/css/v1/cluster/results.go
According to the API reference, we can supports the AZ attribute.
And this is the debug result:
```release-note
1. query response supports az attribute
```
=> feat(css/flavor): query response supports az attribute

openstack/er/v3/attachments/results.go
The JSON label of parameter 'resource_type' is invalid, should be 'json', but got 'q'.
```release-note
```
=> fix(er/attachment): invalid param label for resource type

openstack/ims/v2/cloudimages/requests.go
Support `ImageTags` parameter for `CreateDataImageByOBSOpts` struct
```release-note
Support `ImageTags` parameter for `CreateDataImageByOBSOpts` struct
```
=> feat(ims/images_image): support `ImageTags` parameter for `CreateDataImageByOBSOpts` struct

openstack/ims/v2/cloudimages/requests.go
Support `enterprise_project_id` parameter for `CreateDataImageByServerOpts` struct
```release-note
Support `enterprise_project_id` parameter for `CreateDataImageByServerOpts` struct
```
=> feat(ims): support `enterprise_project_id` parameter for `CreateDataImageByServerOpts` struct

openstack/ims/v2/cloudimages/requests.go
Support `CreateSystemImageByVolumeOpts` struct
```release-note
Support `CreateSystemImageByVolumeOpts` struct
```
=> feat(ims): support `CreateSystemImageByVolumeOpts` struct

openstack/vpcep/v1/endpoints/requests.go, openstack/vpcep/v1/endpoints/results.go
The field (policy_document) type provided in the API document is different from the type returned
by the API, as a result, an error is reported when the resource is imported.
```release-note
```
=> fix(vpcep): remove policy_document field

openstack/workspace/v2/services/requests.go, openstack/workspace/v2/services/results.go
Invalid request parameter keyword `standy`, should be `standby`.
```release-note
1. Invalid request parameter keyword `standy`, should be `standby`.
```
=> fix(workspace/app): the request param keys are invalid for standby domain

openstack/apigw/dedicated/v2/apis/requests.go, openstack/apigw/dedicated/v2/apis/results.go
New orchestration parameters supports for API request parameter structure and backend policy condition.
```release-note
1. API supports new orchestration parameters.
```
=> feat(apig): API supports new orchestration parameters

openstack/servicestage/v1/repositories/requests.go
Update the behavior of the request parameter host, from required to optional, according to the corresponding OpenAPI.
```release-note
1. host behavior is no longer required.
```
=> chore(servicestage/auth): host behavior is no longer required

auth/core/signer/derived_signer.go, auth/derived_signer_helper.go, auth_aksk_options.go, provider_client.go, testing/auth_test.go
golangsdk supports derivative algorithm capabilities.
```
go test -v -run TestSigner_Sign ./testing/
=== RUN   TestSigner_Sign
=== RUN   TestSigner_Sign/test1
=== RUN   TestSigner_Sign/test2
--- PASS: TestSigner_Sign (0.00s)
--- PASS: TestSigner_Sign/test1 (0.00s)
--- PASS: TestSigner_Sign/test2 (0.00s)
PASS
ok      github.com/chnsz/golangsdk/testing      0.007s
```
```
go test -v -run TestDerivedSigner_Sign ./testing/
=== RUN   TestDerivedSigner_Sign
=== RUN   TestDerivedSigner_Sign/test1
=== RUN   TestDerivedSigner_Sign/test2
--- PASS: …
```
=> feat: golangsdk supports derivative algorithm capabilities

openstack/dns/v2/ptrrecords/requests.go
Fixed the issue that the description of PTR record cannot be modified to empty.
```release-note
```
=> fix(dns): fix PTR record description cannot be modified to empty

openstack/apigw/dedicated/v2/channels/requests.go
The parameter reference of the member group name is incorrect, should be 'member_group_name', not 'group_name'.
```release-note
1. update the reference of the param member_group_name.
```
=> fix(apig/channel): update the reference of the param member_group_name

openstack/smn/v2/subscriptions/requests.go
Supplement a parameter 'extension.header' (type map) in to smn request structure.
```release-note
1. new parameter extension.header is supported.
```
=> feat(smn): new parameter extension.header is supported
