chnsz/golangsdk

- provider_client.go
Add 200 in defaultOkCodes to all http methods
> chore(provider_client): Add 200 in defaultOkCodes to all http methods

- provider_client.go
For DIS services, the region name is required to create the signature key.
**Which issue this PR fixes**:
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
```
NONE
```
```release-note
1. add region to signature key generation parameters.
```
```
NONE
```
> fix(sign): add region to signature key generation params

- openstack/identity/v3/groups/requests.go
- openstack/identity/v3/groups/results.go
- openstack/identity/v3/groups/urls.go
support listing users in a user group
> feat(iam/groups): support listing users in a user group

- openstack/dcs/v2/instances/requests.go
- openstack/dcs/v2/instances/results.go
- openstack/dcs/v2/instances/urls.go
- openstack/dcs/v2/tags/requests.go
- openstack/dcs/v2/tags/results.go
- openstack/dcs/v2/tags/urls.go
Add sdk for DCS instances and tags
> feat(dcs): add sdk for DCS instances and tags

- openstack/css/v1/cluster/requests.go
- openstack/css/v1/cluster/results.go
- openstack/css/v1/cluster/urls.go
- openstack/css/v1/snapshots/requests.go
- openstack/css/v1/thesaurus/requests.go
- openstack/css/v1/thesaurus/results.go
- openstack/css/v1/thesaurus/urls.go
- provider_client.go
Add CRUD support to cluster,thesaurus in SDK
fix #1378
> feat(CSS): Add CRUD support to cluster,thesaurus in SDK

- openstack/obs/CHANGELOG
- openstack/obs/README.MD
- openstack/obs/client.go
- openstack/obs/const.go
- openstack/obs/convert.go
- openstack/obs/model.go
- openstack/obs/temporary.go
- openstack/obs/trait.go
sync the sdk from huaweicloud/huaweicloud-sdk-go-obs@v3.21.8
```release-note
```
> Update OBS sdk to v3.21.8

- openstack/obs/CHANGELOG
- openstack/obs/README.MD
> obs: update docs following up dab1291

- openstack/networking/v1/routables/requests.go
- openstack/networking/v1/routables/urls.go
> fix: update the URL and method for Action in route table package

- openstack/dcs/v2/instances/requests.go
add a new http code to the resize request
> fix(dcs): add a new http code to the resize request

- openstack/mrs/v1/cluster/results.go
The query detail api of MRS cluster has add  AssignedRoles field to nodeGroup.
> feat(mrs): add  AssignedRoles field to nodeGroup

- openstack/networking/v1/subnets/requests.go
the [Querying Subnets](https://support.huaweicloud.com/intl/en-us/api-vpc/vpc_subnet01_0003.html) supports to filter subnets by **vpc_id**, add this parameter into query path.
```release-note
```
> fix(subnet): add vpc_id into query path

- openstack/dws/cluster/requests.go
- openstack/dws/cluster/results.go
- openstack/dws/cluster/testing/fixtures.go
- openstack/dws/cluster/testing/requests_test.go
- openstack/dws/cluster/urls.go
Add DWS service api
```
Running tool: /usr/local/go/bin/go test -timeout 30s -run ^(TestList|TestGet|TestNodeType)$ github.com/chnsz/golangsdk/openstack/dws/cluster/testing -v
=== RUN   TestList
--- PASS: TestList (0.00s)
=== RUN   TestGet
--- PASS: TestGet (0.00s)
=== RUN   TestNodeType
--- PASS: TestNodeType (0.00s)
PASS
ok  	github.com/chnsz/golangsdk/openstack/dws/cluster/testing	0.043s
```
> feat(DWS): Add DWS service API

- openstack/dcs/v2/availablezones/requests.go
- openstack/dcs/v2/availablezones/results.go
- openstack/dcs/v2/availablezones/urls.go
Add sdk for querying DCS available zones using API V2
> feat(dcs): add sdk for querying DCS available zones using API V2

- openstack/swr/v2/namespaces/requests.go
- openstack/swr/v2/namespaces/results.go
- openstack/swr/v2/namespaces/urls.go
```release-note
support namespace permissions in sdk
```
> feat(swr): support namespace permissions in sdk

- openstack/cce/v3/nodes/requests.go
- openstack/cce/v3/nodes/urls.go
```release-note
support reset node in sdk
```
> feat(cce/node): support reset node in sdk

- openstack/dcs/v2/instances/requests.go
- openstack/dcs/v2/maintainwindows/requests.go
- openstack/dcs/v2/maintainwindows/results.go
- openstack/dcs/v2/maintainwindows/urls.go
- upgrade the API of DCS maintainwindows to V2.
- fix the DCS resize function: add a new http code to the resize request.
> feat(dcs)  upgrade the API of DCS maintainwindows to V2

- openstack/bms/v1/flavors/requests.go
- openstack/bms/v1/flavors/results.go
- openstack/bms/v1/flavors/testing/requests_test.go
- openstack/bms/v1/flavors/urls.go
testing result as follows:
```
$ go test -v ./
=== RUN   TestListFlavor
--- PASS: TestListFlavor (0.00s)
PASS
ok      github.com/chnsz/golangsdk/openstack/bms/v1/flavors/testing     0.023s
```
> feat(bms): support v1 flavors

- openstack/cci/v1/namespaces/requests.go
- openstack/cci/v1/namespaces/results.go
- openstack/cci/v1/namespaces/urls.go
To support cci namespace resource, we need a namespace sdk. 
**Which issue this PR fixes**:
```
NONE
```
```release-note
1. add new cci namespace sdk support
```
> feat(cci/namespace): add new cci namespace sdk support

- openstack/cce/v3/nodes/requests.go
```release-note
update params of AddNodeSpec
```
> feat(cce/node): update params of AddNodeSpec

- openstack/cce/v1/persistentvolumeclaims/requests.go
- openstack/cce/v1/persistentvolumeclaims/results.go
- openstack/cce/v1/persistentvolumeclaims/urls.go
> refactor(cce/pvc): use kubernetes API

- openstack/dis/v2/streams/requests.go
- openstack/dis/v2/streams/results.go
- openstack/dis/v2/streams/testing/fixtures.go
- openstack/dis/v2/streams/testing/requests_test.go
- openstack/dis/v2/streams/urls.go
- openstack/dis/v3/streams/requests.go
- openstack/dis/v3/streams/urls.go
> feat(DIS): add dis service api

- openstack/swr/v2/domains/requests.go
- openstack/swr/v2/domains/results.go
- openstack/swr/v2/domains/urls.go
add sdk of swr domains v2
```release-note
```
> feat(swe/domains): add sdk of swr domains v2

- openstack/dli/v1/auth/requests.go
- openstack/dli/v1/auth/results.go
- openstack/dli/v1/auth/urls.go
those api can assign the permissions and query permissions
> feat(DLI): add DLI auth API

- openstack/dli/v1/auth/requests.go
- openstack/dli/v1/auth/results.go
- openstack/dli/v1/flinkjob/results.go
1. remove the json tag from `CommonResp`
2. fix httpMethod
3. delete useless code
> fix(DLI): fix json type and httpMethod; delete useless code

- openstack/kms/v1/keys/requests.go
- openstack/kms/v1/keys/results.go
> feat(kms): add key_spec to kms key

- openstack/cce/v3/clusters/requests.go
support enterprise_project_id in listing clusters
```release-note
support enterprise_project_id in listing clusters
```
> feat(cce/clusters): support enterprise_project_id in listing clusters

- openstack/eps/v1/enterpriseprojects/requests.go
- openstack/eps/v1/enterpriseprojects/results.go
- openstack/eps/v1/enterpriseprojects/urls.go
add functions Create, Get, Update and Action in EPS
```release-note
add functions Create, Get, Update and Action in EPS
```
> feat(eps): add functions Create, Get, Update and Action in EPS

- openstack/rds/v3/instances/requests.go
- openstack/rds/v3/instances/results.go
- openstack/rds/v3/instances/urls.go
Add a new method to support the RDS engine versions acquirement.
```
NONE
```
```release-note
1. Add a new method and related response structure of versions acquirement
```
> feat(rds/engine): add new method of versions acquirement

- openstack/taurusdb/v3/instances/requests.go
- openstack/taurusdb/v3/instances/results.go
> fix(gaussdb/mysql): update public_ips type

- openstack/cci/v1/networks/requests.go
> Revert "fix: style: update the cidr of the specification"

- openstack/mrs/v1/cluster/results.go
add three field in result which it's not in document
> chore(MRS): add three field in result which it's not in document

- openstack/iec/v1/bandwidths/requests.go
- openstack/iec/v1/bandwidths/results.go
- openstack/iec/v1/bandwidths/urls.go
- openstack/iec/v1/common/common.go
> feat(iec): support list bandwidth APIs

- openstack/rds/v3/flavors/requests.go
- openstack/rds/v3/flavors/results.go
add some parameter in flavors api
> feat(rds): add some parameter in flavors api

- openstack/fgs/v2/function/requests.go
- openstack/fgs/v2/function/results.go
Missing parameter encrypted user data in the request and response structure.
```
NONE
```
```release-note
1. add encrypted user data support to request and response structure.
```
> feat(fgs/function): add encrypted user data support

- openstack/dms/v2/kafka/instances/requests.go
- openstack/dms/v2/kafka/instances/urls.go
add the method of resizing the capacity for Kafka instances.
> feat(dms): add the method of resizing the capacity

- openstack/cdm/v1/clusters/requests.go
- openstack/cdm/v1/clusters/results.go
- openstack/cdm/v1/clusters/urls.go
support CDM clusters services
```release-note
```
> feat(CDM):support CDM clusters services

- openstack/networking/v1/eips/requests.go
- openstack/networking/v1/eips/results.go
chore the API: query EIPs 
1. Change some parameters from strings to arrays:PortId/PublicIp/PrivateId
2.  add some parameter: id/AllowShareBandwidthTypeAny/alias/IpVersion/PublicIpv6Address
> chore(EIP): Change some parameters from strings to arrays in the List API

- openstack/networking/v1/eips/results.go
fix the type of ipversion in results
> fix(EIP): fix the type of ipversion in results

- openstack/dms/v2/availablezones/requests.go
- openstack/dms/v2/availablezones/results.go
- openstack/dms/v2/availablezones/urls.go
- openstack/dms/v2/maintainwindows/requests.go
- openstack/dms/v2/maintainwindows/results.go
- openstack/dms/v2/maintainwindows/urls.go
- openstack/dms/v2/products/requests.go
- openstack/dms/v2/products/results.go
- openstack/dms/v2/products/urls.go
upgrade the API version of the query product and maintain windows to V2
> [DMS] upgrade the API version of the query product and maintain windows to V2

- openstack/networking/v1/eips/results.go
The response structure is missing bandwidth name.
```
NONE
```
```release-note
1. add bandwidth name to the response structure
```
> feat(eip): add bandwidth name to the response structure

- openstack/dms/v2/availablezones/urls.go
- openstack/dms/v2/products/results.go
fix the url of the API for querying the DMS availability zones
> fix(dms): fix the url of the API for querying the DMS availability zones

- openstack/cdm/v1/link/requests.go
- openstack/cdm/v1/link/results.go
- openstack/cdm/v1/link/urls.go
support link resource
```release-note
```
> feat(CDM): support link resource

- openstack/elb/v3/pools/requests.go
> fix(elb/pool): make name and description be a pointer

- openstack/networking/v1/eips/requests.go
API docs:
- https://support.huaweicloud.com/api-eip/eip_api_0001.html
- https://support.huaweicloud.com/api-eip/eip_api_0004.html
```release-note
```
> feat: support alias and ip_version parameters for eip

- openstack/dli/v1/queues/requests.go
- openstack/dli/v1/queues/results.go
support change the CIDR in VPC
```release-note
```
> feat(DLI): support change the CIDR in VPC

- openstack/ecs/v1/cloudservers/requests.go
API docs: https://support.huaweicloud.com/api-ecs/ecs_02_0101.html#ecs_02_0101__table9120223
```release-note
```
> feat: support ipv6 for ecs nics

- openstack/cdm/v1/job/requests.go
- openstack/cdm/v1/job/results.go
- openstack/cdm/v1/job/urls.go
support the CDM job service
```release-note
```
> feat(CDM): support cdm job service

- openstack/ecs/v1/cloudservers/requests.go
ipv6_bandWidth --> ipv6_bandwidth
```release-note
```
> fix(ecs): update json tag of Nic.BandWidth

- openstack/elb/v2/listeners/requests.go
- openstack/elb/v2/listeners/results.go
- openstack/elb/v2/listeners/urls.go
add elb listeners v2 sdk
```release-note
add elb listeners v2 sdk
```
> feat(elb/listeners): add elb listeners v2 sdk

- openstack/elb/v2/certificates/request.go
- openstack/elb/v2/certificates/results.go
- openstack/elb/v2/certificates/urls.go
complete the v2 sdk of elb certificates
```release-note
add functions: Create, Get, Update, Delete
```
> feat(elb/certificates): complete the v2 sdk of elb certificates

- openstack/elb/v2/pools/requests.go
- openstack/elb/v2/pools/results.go
- openstack/elb/v2/pools/urls.go
add elb pools v2 sdk
```release-note
add elb pools v2 sdk
```
> feat(elb/pools): add elb pools v2 sdk

- openstack/csms/v1/secrets/requests.go
- openstack/csms/v1/secrets/results.go
- openstack/csms/v1/secrets/urls.go
> feat(csms): add SDK support for CSMS API

- openstack/networking/v1/bandwidths/requests.go
- openstack/networking/v1/bandwidths/results.go
- openstack/networking/v2/bandwidths/requests.go
> feat: add ChargeMode field into CreateOpts of bandwidth

- openstack/dms/v1/instances/results.go
please get the response body from: https://support.huaweicloud.com/en-us/api-kafka/kafka-api-180514003.html
```release-note
```
> dms: add more attributes in response struct

- openstack/elb/v2/l7policies/requests.go
- openstack/elb/v2/l7policies/results.go
- openstack/elb/v2/l7policies/urls.go
add elb l7policies v2 sdk
```release-note
add elb l7policies v2 sdk
```
> feat(elb/l7policies): add elb l7policies v2 sdk

- openstack/elb/v2/monitors/requests.go
- openstack/elb/v2/monitors/results.go
- openstack/elb/v2/monitors/urls.go
add elb monitors v2 sdk
```release-note
add elb monitors v2 sdk
```
> feat(elb/monitors): add elb monitors v2 sdk

- openstack/elb/v2/whitelists/requests.go
- openstack/elb/v2/whitelists/results.go
- openstack/elb/v2/whitelists/urls.go
add elb whitelists v2 sdk
```release-note
add elb whitelists v2 sdk
```
> feat(elb/whitelists): add elb whitelists v2 sdk

- openstack/cce/v3/nodes/results.go
add parameter 'storage' in cce node
```release-note
add parameter 'storage' in cce node
```
> feat(cce/node): add parameter 'storage' in cce node

- openstack/modelarts/v1/notebook/requests.go
- openstack/modelarts/v1/notebook/results.go
- openstack/modelarts/v1/notebook/urls.go
- pagination/offset.go
support notebook service
```release-note
```
> feat(modelArts): support notebook service

- openstack/obs/client_bucket.go
- openstack/obs/const.go
- openstack/obs/convert.go
- openstack/obs/model_base.go
- openstack/obs/model_bucket.go
- openstack/obs/trait.go
> feat: support bucket cross-region replication configuration

- openstack/ims/v2/cloudimages/requests.go
add parameter enterprise_project_id in ListOpts of images
```release-note
add parameter enterprise_project_id in ListOpts of images
```
> feat(ims/cloudimages): add parameter enterprise_project_id in ListOpts of images

- openstack/networking/v1/vpcs/requests.go
move enterprise_project_id to List query
```release-note
move enterprise_project_id to List query
```
**Test results**:
```
go test ./openstack/networking/v1/vpcs/testing -v -run Test
=== RUN   TestListVpc
--- PASS: TestListVpc (0.00s)
=== RUN   TestGetVpc
--- PASS: TestGetVpc (0.00s)
=== RUN   TestCreateVpc
--- PASS: TestCreateVpc (0.00s)
=== RUN   TestUpdateVpc
--- PASS: TestUpdateVpc (0.00s)
=== RUN   TestDeleteVpc
--- PASS: TestDeleteVpc (0.01s)
PASS
ok      github.com/chnsz/golangsdk/openstack/networking/v1/vpcs/testing 0.062s
```
> refactor(vpc): move enterprise_project_id to List query

- openstack/rms/v1/resources/requests.go
- openstack/rms/v1/resources/results.go
- openstack/rms/v1/resources/urls.go
- pagination/marker.go
add RMS list API 
```release-note
```
> feat(RMS): add RMS list API support

- openstack/networking/v2/extensions/lbaas_v2/listeners/requests.go
- openstack/networking/v2/extensions/lbaas_v2/loadbalancers/requests.go
```release-note
$ go test -v ./openstack/networking/v2/extensions/lbaas_v2/listeners/testing/
=== RUN   TestListListeners
--- PASS: TestListListeners (0.00s)
=== RUN   TestListAllListeners
--- PASS: TestListAllListeners (0.00s)
=== RUN   TestCreateListener
--- PASS: TestCreateListener (0.00s)
=== RUN   TestRequiredCreateOpts
--- PASS: TestRequiredCreateOpts (0.00s)
=== RUN   TestGetListener
--- PASS: TestGetListener (0.00s)
=== RUN   TestDeleteListener
--- PASS: TestDeleteListener (0.00s)
=== RUN   TestUpdateListener
--- PASS: …
```
> bugfix(lbaas): change type of Description to pointer in UpdateOpts

- openstack/drs/v3/jobs/requests.go
- openstack/drs/v3/jobs/results.go
- openstack/drs/v3/jobs/urls.go
add DRS api support
```release-note
```
> feat(DRS): add DRS api support

- openstack/cloudeyeservice/alarmrule/requests.go
update CreateOpts of alarmrule
```release-note
update CreateOpts of alarmrule
```
> refactor(ces/alarmrule): update CreateOpts of alarmrule

- openstack/evs/v2/cloudvolumes/requests.go
- openstack/evs/v2/cloudvolumes/results.go
- openstack/modelarts/v1/notebook/requests.go
- openstack/modelarts/v1/notebook/results.go
- pagination/offset.go
The current design of `OffsetPageBase` is inconsistent with the design style of other `PageBase`s. After the change, users can directly use or override the `LastOffset()` and `NextPageURL()` functions to achieve the same effect as `MarkerPageBase`.
```release-note
1. refactor functions of OffsetPageBase.
2. replace marker page with offset page for evs volume sdk.
```
> refactor(pagination): refactor offset page methods and structures

- openstack/modelarts/v1/notebook/requests.go
add an empty body to start func, when auth by aksk, 
```release-note
```
> feat(modealArt): add an empty body to start func

- openstack/autoscaling/v1/groups/requests.go
add EnterpriseProjectID in ListOpts
```release-note
add EnterpriseProjectID in ListOpts
```
> feat(as/groups): add EnterpriseProjectID in ListOpts

- openstack/ecs/v1/block_devices/requests.go
- openstack/ecs/v1/block_devices/results.go
- openstack/ecs/v1/block_devices/urls.go
- openstack/ecs/v1/jobs/requests.go
- openstack/ecs/v1/jobs/results.go
- openstack/ecs/v1/jobs/urls.go
The method provided by the current V1 version of the block device package is not enough to support the research and development needs of disk mounting.
```
NONE
```
```release-note
1. add new jobs sdk support.
2. refactor block_device sdk methods.
```
> refactor:feat(ecs/volume): add new methods to support disk mount

- openstack/fgs/v2/dependencies/requests.go
- openstack/fgs/v2/dependencies/testing/fixtures.go
- openstack/fgs/v2/dependencies/testing/requests_test.go
- openstack/fgs/v2/dependencies/urls.go
The functional capabilities provided by the current SDK are not enough to support the complete management process of dependent packages.
```release-note
1. add new dependent package methods.
```
> feat(fgs/dependency): add new dependent package methods

- openstack/modelarts/v2/dataset/requests.go
- openstack/modelarts/v2/dataset/results.go
- openstack/modelarts/v2/dataset/urls.go
add dataset api support
```release-note
```
> feat(ModelArts): add dataset api support

- openstack/elb/v3/loadbalancers/requests.go
- openstack/elb/v3/loadbalancers/results.go
support prepaid in loadbalancers
```release-note
support prepaid in loadbalancers
```
> feat(elb/loadbalancers): support prepaid in loadbalancers

- openstack/networking/v1/ports/requests.go
- openstack/networking/v1/ports/results.go
- openstack/networking/v1/ports/testing/fixtures.go
- openstack/networking/v1/ports/testing/requests_test.go
- openstack/networking/v1/ports/urls.go
Add new v1 version sdk support for VPC networking VIP.
```release-note
1. add new sdk support.
```
> feat(networking/vip): add new sdk support for VPC networking VIP

- openstack/fgs/v2/function/requests.go
- openstack/fgs/v2/function/results.go
Add a new parameter `type` to support the function version specifying.
```release-note
1. A new parameter is supported: type.
```
> feat(fgs/function): Add new parameter to specify version type

- openstack/cloudeyeservice/alarmrule/requests.go
- openstack/cloudeyeservice/alarmrule/results.go
add suppress_duration support in alarm rule
```release-note
add suppress_duration support in alarm rule
```
> feat(cce/alarmrule): add suppress_duration support in alarm rule

- openstack/css/v1/cluster/results.go
The sdk needs to be updated due to the recent CSS API update to the json name of the enterprise project ID parameter.
```release-note
1. update json name about enterprise project parameter.
```
> fix(css/cluster): update json name about eps param

- openstack/networking/v1/ports/testing/fixtures.go
- openstack/networking/v1/ports/testing/requests_test.go
- openstack/networking/v1/ports/urls.go
- openstack/networking/v1/security/rules/urls.go
- openstack/networking/v1/security/securitygroups/urls.go
uniform the request's urls for vpc client.
```release-note
```
> refactor(vpc/urls): add project id to the request's url

- openstack/networking/v1/ports/requests.go
- openstack/networking/v1/ports/results.go
- openstack/networking/v1/ports/testing/fixtures.go
- openstack/networking/v1/ports/testing/requests_test.go
```
$ go test -v
=== RUN   TestCreateV1NetworkPort
--- PASS: TestCreateV1NetworkPort (0.00s)
=== RUN   TestGetV1NetworkPort
--- PASS: TestGetV1NetworkPort (0.00s)
=== RUN   TestUpdateV1NetworkPort
--- PASS: TestUpdateV1NetworkPort (0.00s)
=== RUN   TestDeleteV1NetworkPort
--- PASS: TestDeleteV1NetworkPort (0.00s)
=== RUN   TestListV1NetworkPort
--- PASS: TestListV1NetworkPort (0.00s)
PASS
ok      github.com/chnsz/golangsdk/openstack/networking/v1/ports/testing        0.015s
```
```release-note
```
> feat(ports): add List support and testing case

- openstack/servicestage/v2/environments/requests.go
- openstack/servicestage/v2/environments/results.go
- openstack/servicestage/v2/environments/urls.go
Support new sdk for ServiceStage environment.
```release-note
1. add a new environment sdk.
```
> feat(servicestage/env): add new environment sdk support

- openstack/ecs/v1/cloudservers/results.go
add Fault in CloudServer struct
```release-note
add Fault in CloudServer struct
```
> feat(ecs): add Fault in CloudServer struct

- openstack/autoscaling/v1/configurations/requests.go
- rename some fields as they are harding understanding
- support to create an eip with existing shared bandwidth
```release-note
```
> feat(as): support to create an eip with existing shared bandwidth

- openstack/autoscaling/v1/groups/requests.go
- openstack/autoscaling/v1/groups/results.go
- openstack/autoscaling/v1/groups/urls.go
> feat(as): support ForceDelete method

- openstack/servicestage/v1/repositories/requests.go
- openstack/servicestage/v1/repositories/results.go
- openstack/servicestage/v1/repositories/urls.go
Support a new sdk for repositories authorization.
```release-note
1. add new repository authorization sdk.
2. support two authorizations: password and personal access token.
```
> feat(servicestage): add new repository authorization sdk

- openstack/cts/v1/tracker/requests.go
> fix(cts): support to filter tracker by name

- openstack/apigw/dedicated/v2/instances/results.go
> Revert "fix(apig/egress): rename extract method and support a new one"

- openstack/elb/v3/loadbalancers/requests.go
support prepaid in UpdateOpts
```release-note
support prepaid in UpdateOpts
```
> feat(elb/loadbalancer): support prepaid in UpdateOpts

- openstack/servicestage/v2/components/requests.go
- openstack/servicestage/v2/components/results.go
- openstack/servicestage/v2/components/urls.go
This sdk support the CRUD of ServiceStage component to management resources.
```release-note
1. Add new component sdk support for ServiceStage service.
```
> feat(servicestage): add new component sdk support

- openstack/servicestage/v2/metadata/requests.go
- openstack/servicestage/v2/metadata/results.go
- openstack/servicestage/v2/metadata/urls.go
This sdk is use to query component runtimes or application flavors.
```release-note
1. add new meta sdk support.
```
> feat(servicestage): add new meta sdk support

- openstack/modelarts/v2/version/requests.go
- openstack/modelarts/v2/version/results.go
- openstack/modelarts/v2/version/urls.go
support dataset version APIs
```release-note
```
> feat(Modelarts): support dataset version APIs

- openstack/antiddos/v1/antiddos/requests.go
- openstack/antiddos/v1/antiddos/results.go
- openstack/antiddos/v1/antiddos/testing/fixtures.go
```release-note
```
```
/openstack/antiddos/v1/antiddos/testing (enhance) $ go test -v ./
=== RUN   TestCreate
--- PASS: TestCreate (0.00s)
=== RUN   TestDelete
--- PASS: TestDelete (0.00s)
=== RUN   TestGet
--- PASS: TestGet (0.00s)
=== RUN   TestUpdate
--- PASS: TestUpdate (0.00s)
=== RUN   TestListStatus
--- PASS: TestListStatus (0.00s)
=== RUN   TestListConfigs
--- PASS: TestListConfigs (0.00s)
=== RUN   TestWeeklyReport
--- PASS: TestWeeklyReport (0.00s)
=== RUN   TestListLogs
--- PASS: TestListLogs (0.00s)
=== RUN   TestGetStatus …
```
> feat(antiddos): add more attributes in ListStatus response

- openstack/taurusdb/v3/auditlog/requests.go
- openstack/taurusdb/v3/auditlog/results.go
- openstack/taurusdb/v3/auditlog/urls.go
> feat(gaussdb): add auditlog api support

- openstack/ecs/v1/cloudservers/requests.go
add metadata in RootVolume and DataVolume
```release-note
add metadata in RootVolume and DataVolume
```
> feat(ecs): add metadata in RootVolume and DataVolume

- openstack/networking/v1/subnets/requests.go
- openstack/networking/v1/subnets/results.go
> feat(subnet): support description options

- openstack/ecs/v1/cloudservers/requests.go
- openstack/ecs/v1/cloudservers/results.go
> feat(ecs/cloudservers): add __support_agent_list to metadata

- openstack/rds/v3/instances/requests.go
- openstack/rds/v3/instances/results.go
> fix(rds): fix instance auto_pay issue

- openstack/ecs/v1/cloudservers/requests.go
API documentation
https://support.huaweicloud.com/api-ecs/zh-cn_topic_0167957246.html#ZH-CN_TOPIC_0167957246__section1846944811410
```release-note
```
> feat(ecs): add delete_on_termination support when creating EIP

- openstack/servicestage/v2/instances/requests.go
- openstack/servicestage/v2/instances/results.go
- openstack/servicestage/v2/instances/urls.go
- openstack/servicestage/v2/jobs/requests.go
- openstack/servicestage/v2/jobs/results.go
- openstack/servicestage/v2/jobs/urls.go
The related sdk of the component deployment resource for ServiceStage service.
```release-note
1. support new instance sdk support.
```
> feat(servicestage): add new instance sdk support

- openstack/sms/v3/templates/requests.go
- openstack/sms/v3/templates/results.go
- openstack/sms/v3/templates/urls.go
> feat(sms): add templates SDK support

- openstack/cse/dedicated/v2/engines/requests.go
- openstack/cse/dedicated/v2/engines/results.go
- openstack/cse/dedicated/v2/engines/urls.go
> feat(cse): add a new microservice sdk support

- openstack/sms/v3/sources/requests.go
- openstack/sms/v3/sources/results.go
- openstack/sms/v3/sources/urls.go
> feat(sms): support to list source servers

- openstack/cse/dedicated/v2/engines/results.go
There is a problem with the structure definition of entrypoint in the API documentation, and now it is adjusted according to the actual API calling structure.
```release-note
1. readjust the entrypoint structure.
```
> fix(microservice): adjust the entrypoint structure

- openstack/networking/v2/extensions/hw_snatrules/requests.go
- openstack/networking/v2/extensions/hw_snatrules/results.go
> feat(snat): add update method

- openstack/sms/v3/sources/requests.go
- openstack/sms/v3/sources/results.go
- openstack/sms/v3/sources/urls.go
- openstack/sms/v3/tasks/requests.go
- openstack/sms/v3/tasks/results.go
> fix(sms): change type of MigrateSpeed to float32

- openstack/kms/v1/rotation/requests.go
- openstack/kms/v1/rotation/results.go
- openstack/kms/v1/rotation/urls.go
> feat(kms): add key rotation SDK support

- openstack/lts/v2/loggroups/requests.go
- openstack/lts/v2/logtopics/requests.go
> fix(lts): add Content-type header for DELETE to fix waf issue

- openstack/apigw/dedicated/v2/apis/requests.go
- openstack/apigw/dedicated/v2/apis/urls.go
- openstack/apigw/dedicated/v2/throttles/requests.go
- openstack/apigw/dedicated/v2/throttles/results.go
- openstack/apigw/dedicated/v2/throttles/urls.go
Add three methods to support throttling policies binding.
- Bind
- Unbind
- ListBind
```release-note
1. add three methods to support throttling policies binding.
```
> feat(apig/throttle): support policy binding

- openstack/meeting/v1/auth/requests.go
- openstack/meeting/v1/auth/results.go
- openstack/meeting/v1/auth/urls.go
- openstack/meeting/v1/conferences/requests.go
- openstack/meeting/v1/conferences/results.go
- openstack/meeting/v1/conferences/urls.go
- openstack/meeting/v2/auth/requests.go
- openstack/meeting/v2/auth/results.go
- openstack/meeting/v2/auth/urls.go
support the authorization sdks (ver.1 and ver.2) and the conference sdk.
```release-note
1. add new conference sdk and authorization sdks for meeting service.
```
> feat(meeting/conference): support conference sdks

- params.go
Ignore query parameters in `BuildRequestBody` method.
```release-note
1. ignore query parameters in build method
```
> chore(body/build): ignore query parameters in build method

- openstack/client.go
> feat: add sfs turbo v1 client

- openstack/meeting/v1/assignments/requests.go
- openstack/meeting/v1/assignments/results.go
- openstack/meeting/v1/assignments/urls.go
Add new role assignment sdk support.
```release-note
1. add new role assignment sdk support.
```
> feat(meeting): add new role assignment sdk support

- openstack/identity/v3/users/results.go
> feat(iam/users): add more attributes in API response

- openstack/dds/v3/roles/requests.go
- openstack/dds/v3/roles/results.go
- openstack/dds/v3/roles/urls.go
> feat(dds/role): add new database role sdk support

- openstack/dds/v3/users/requests.go
- openstack/dds/v3/users/results.go
- openstack/dds/v3/users/urls.go
> feat(dds/user): add new database user sdk support

- openstack/servicestage/v2/instances/requests.go
- openstack/servicestage/v2/instances/results.go
Add a new policies parameter.
```release-note
```
> feat(log/collection): support new policies parameter

- openstack/dds/v3/users/requests.go
- openstack/dds/v3/users/results.go
> refactor(role/refer): using role structure references

- openstack/servicestage/v2/instances/requests.go
- openstack/servicestage/v2/instances/results.go
> feat(servicestage): fix the parameter problems

- openstack/evs/v2/snapshots/results.go
* Adjust the field type according to the document
* fix query snapshot list  error
```release-note
```
> fix: change PageList Links field type slice

- openstack/ecs/v1/cloudservers/requests.go
- openstack/ecs/v1/cloudservers/results.go
- openstack/ecs/v1/cloudservers/urls.go
support resetting password in ecs v1 sdk
```release-note
support resetting password in ecs v1 sdk
```
> feat(ecs): support resetting password in ecs v1 sdk

- openstack/aad/v1/rules/requests.go
- openstack/aad/v1/rules/results.go
- openstack/aad/v1/rules/urls.go
Add new Advanced DDoS forward rule sdk support.
```release-note
1. add new Advanced DDoS forward rule sdk support.
```
> feat(aad/rule): support the forward rule sdk

- pagination/offset.go
get next offset according to the following priority:
query path > current page size > DefaultLimit
the testing is successful in huaweicloud provider of EVS data source
```release-note
```
> feat(pager/offset): calc the next offset from query path or current page size

- pagination/marker.go
- pagination/pagesize.go
> feat(pager): get next marker field

- pagination/list_all.go
> feat(pager): add a new method to query all items

- openstack/bss/v2/resources/requests.go
- openstack/bss/v2/resources/results.go
- openstack/bss/v2/resources/urls.go
Add new prepaid resource sdk support:
- Get method: query the specified prepaid resource.
- EnableAutoRenew method: enable auto-renew.
- DisableAutoRenew method: disable auto-renew.
```release-note
1. add new prepaid resource sdk support.
```
> feat(bss/resources): add new prepaid resource sdk support

- openstack/dms/v2/kafka/instances/requests.go
- openstack/dms/v2/kafka/instances/results.go
- openstack/dms/v2/kafka/instances/urls.go
Support advertised IP modification of cross-VPC.
```release-note
```
> feat(dms/kafka): support the cross-vpc modification

- openstack/dds/v3/instances/requests.go
update the sdk to support prePaid
```release-note
update the sdk to support prePaid
```
> feat(dds/instances): update the sdk to support prePaid

- openstack/ecs/v1/cloudservers/requests.go
- openstack/ecs/v1/cloudservers/results.go
- openstack/ecs/v1/cloudservers/urls.go
support Update in ecs v1 sdk
```release-note
support Update in ecs v1 sdk
```
> feat(ecs): support Update in ecs v1 sdk

- openstack/bss/v2/resources/requests.go
> feat(BSS): add a method to query resource of order

- openstack/fgs/v2/function/requests.go
- openstack/fgs/v2/function/results.go
- support new parameter:
- CustomImage
- change the behavior from required to optional
- code_type
```release-note
```
> feat(fgs/function): support for creating functions by image

- .github/workflows/ci.yml
> chore(ci/yml): update the go version for import check

- .github/workflows/ci.yml
- openstack/opengauss/v3/instances/requests.go
- openstack/opengauss/v3/instances/results.go
Support a unified update method to instead of UpdateCluster method and UpdateVolume method.
```release-note
```
> feat(gaussdb/opengauss): support a unified update method

- .github/workflows/ci.yml
- openstack/opengauss/v3/instances/requests.go
- openstack/opengauss/v3/instances/results.go
> feat(gaussdb/opengauss): support replica num parameter

- openstack/geminidb/v3/instances/requests.go
- openstack/opengauss/v3/instances/requests.go
- openstack/taurusdb/v3/instances/requests.go
> refactor(db/instance): using 404 error to mark resource not found

- openstack/sfs_turbo/v1/shares/requests.go
- openstack/sfs_turbo/v1/shares/results.go
sfsturbo add request and response body. use it to query volume list、expand volume
```release-note
```
> fix: sfs turbo add request and response

- openstack/cce/v3/clusters/requests.go
update func UpdateMasterIp
```release-note
replace &r.Body with nil because we don't need the api response, and this can avoid error when the api response is empty
```
> refactor(cce/cluster): update func UpdateMasterIp

- openstack/workspace/v2/desktops/requests.go
- openstack/workspace/v2/desktops/results.go
- openstack/workspace/v2/desktops/urls.go
- openstack/workspace/v2/jobs/requests.go
- openstack/workspace/v2/jobs/results.go
- openstack/workspace/v2/jobs/urls.go
Support the desktop and job packages.
```release-note
```
> feat(workspace/desktop): add new resource sdk support

- openstack/workspace/v2/users/requests.go
- openstack/workspace/v2/users/results.go
- openstack/workspace/v2/users/urls.go
> feat(workspace/user): add new resource sdk support

- openstack/kms/v3/keypairs/requests.go
- openstack/kms/v3/keypairs/results.go
- openstack/kms/v3/keypairs/urls.go
> feat(kms): add keypair task support

- openstack/dcs/v1/products/results.go
- openstack/dcs/v2/flavors/results.go
> feat(dcs): add more attributes in list flavors response

- openstack/elb/v3/loadbalancers/requests.go
- openstack/elb/v3/loadbalancers/results.go
> add autoscaling to elb

- openstack/dcs/v1/instances/requests.go
add Port and SpecCode in v1 sdk
```release-note
add Port and SpecCode in v1 sdk
```
> feat(dcs/instances): add Port and SpecCode in v1 sdk

- openstack/dms/v1/instances/requests.go
- openstack/dms/v1/instances/results.go
update v1 sdk to support enable_auto_topic
```release-note
update v1 sdk to support enable_auto_topic
```
> feat(dms/instances): update v1 sdk to support enable_auto_topic

- openstack/rds/v3/instances/requests.go
> fix replica ok code

- openstack/dayu/v1/instances/requests.go
- openstack/dayu/v1/instances/results.go
- openstack/dayu/v1/instances/urls.go
> feat: add dayu instances sdk support

- openstack/elb/v3/logtanks/requests.go
- openstack/elb/v3/logtanks/results.go
- openstack/elb/v3/logtanks/urls.go
> add elb logtanks

- openstack/apigw/dedicated/v2/instances/requests.go
- openstack/apigw/dedicated/v2/instances/results.go
According to the latest API documentation, we append a few parameters to the sdk request structure.
```release-note
1. new parameters are support.
```
> feat(apig/instance): new parameters are support

- openstack/apigw/dedicated/v2/instances/requests.go
- openstack/apigw/dedicated/v2/instances/testing/fixtures.go
The description can set an empty value via 'Update' method.
So, the parameter behavior should be a pointer.
```release-note
1. update the behavior of parameter 'description'
```
> refactor(apig/instance): update the behavior of parameter 'description'

- openstack/identity/v3/roles/requests.go
- openstack/identity/v3/roles/results.go
Added a new function to handle duplicates in pagination returns.
```release-note
1. support new method to deduplicate the role list.
```
> fix(iam/roles): support new method to deduplicate the role list

- openstack/ecs/v1/cloudservers/requests.go
> feat(ecs): add parameters about spot price

- openstack/rds/v3/instances/requests.go
- openstack/rds/v3/instances/results.go
- openstack/rds/v3/instances/urls.go
> feat(RDS): support reset password

- openstack/cloudeyeservice/alarmrule/requests.go
- openstack/cloudeyeservice/alarmrule/results.go
> fix(ces): update condition.value to float64

- openstack/servicestage/v2/instances/requests.go
The name of the parameter structure just the configuration name, not secret name.
The secret has the corresponding parameter 'secretName'.
```release-note
NONE
```
> feat(servicestage/instance): Support new parameter secret name

- openstack/er/v3/vpcattachments/requests.go
- openstack/er/v3/vpcattachments/results.go
- openstack/er/v3/vpcattachments/urls.go
Support new sdk of the VPC attachment for ER service.
```release-note
NONE
```
> feat(er/attachment): add new VPC attachment sdk support

- openstack/cce/v3/nodepools/requests.go
- openstack/cce/v3/nodepools/results.go
support PodSecurityGroups in node pool
```release-note
support PodSecurityGroups in node pool
```
> feat(cce): support PodSecurityGroups in node pool

- openstack/ims/v2/cloudimages/requests.go
- openstack/ims/v2/cloudimages/results.go
add input and output params to cloud image
```release-note
add input and output params to cloud image
```
> feat: add ims params

- openstack/geminidb/v3/instances/results.go
> feat(geminidb): add lb_ip_address and lb_port

- openstack/autoscaling/v1/configurations/requests.go
- openstack/autoscaling/v1/configurations/results.go
- openstack/autoscaling/v1/groups/requests.go
- openstack/autoscaling/v1/groups/results.go
> feat(as): support more parameters of groups and configurations

- openstack/elb/v3/pools/results.go
add elb pool v3 param of persistence_timeout
```release-note
add elb pool v3 param of persistence_timeout
```
> elb pool v3 add param

- openstack/rf/v1/stacks/requests.go
- openstack/rf/v1/stacks/results.go
- openstack/rf/v1/stacks/urls.go
Support new sdk for AOS service.
```release-note
1. add new sdk support
```
> feat(rf/stack): add new sdk support

- openstack/cse/dedicated/v2/engines/requests.go
Add enterprise project ID to the request header.
```release-note
1. Add enterprise project ID to the request header.
```
> fix(cse/engine): add eps id to the request header

- openstack/waf_hw/v1/premium_instances/requests.go
add param ResTenant in dedicated instance
```release-note
add param ResTenant in dedicated instance
```
> feat(waf): add param ResTenant in dedicated instance

- openstack/dc/v3/gateways/requests.go
- openstack/dc/v3/gateways/results.go
- openstack/dc/v3/gateways/urls.go
support new sdk of virtual gateway
```release-note
```
> feat(dc/gateway): support new sdk of virtual gateway

- .github/workflows/ci.yml
- script/format
> feat: use gofmt to check code format

- openstack/obs/README.MD
- openstack/obs/client_base.go
- openstack/obs/client_bucket.go
- openstack/obs/client_object.go
- openstack/obs/client_other.go
- openstack/obs/client_part.go
- openstack/obs/conf.go
- openstack/obs/const.go
- openstack/obs/convert.go
- openstack/obs/http.go
- openstack/obs/log.go
- openstack/obs/model_base.go
- openstack/obs/model_bucket.go
- openstack/obs/model_object.go
- openstack/obs/temporary_createSignedUrl.go
- openstack/obs/trait.go
- openstack/obs/transfer.go
update obs sdk to 3.22.11
```release-note
```
> Obs sdk up

- openstack/dc/v3/interfaces/requests.go
- openstack/dc/v3/interfaces/results.go
- openstack/dc/v3/interfaces/urls.go
add new sdk support for DC service.
```release-note
```
> feat(dc/interface): add new sdk support

- openstack/waf/v1/clouds/requests.go
- openstack/waf/v1/clouds/results.go
- openstack/waf/v1/clouds/urls.go
Add new sdk support for cloud WAF.
```release-note
```
> feat(waf/cloud): add new sdk support

- openstack/eps/v1/enterpriseprojects/requests.go
- openstack/eps/v1/enterpriseprojects/results.go
- openstack/eps/v1/enterpriseprojects/urls.go
add eps migrate method
```release-note
```
> feat:add eps migrate method

- openstack/dayu/v1/instances/requests.go
- openstack/dayu/v1/instances/results.go
fix dayu request and result param
```release-note
fix dayu request and result param
```
> fix: fix dayu request and result param

- openstack/waf_hw/v1/domains/requests.go
> feat(waf): add a new parameter PaidType in cloud domain CreateOpts

- openstack/dms/v2/kafka/instances/requests.go
- openstack/dms/v2/rabbitmq/instances/requests.go
- openstack/dms/v2/rabbitmq/instances/urls.go
add new parameters to resizing API
```release-note
```
> add new parameters to resizing API

- openstack/waf_hw/v1/premium_instances/requests.go
waf instance support epsId
```release-note
```
> fix: waf instance support epsId

- openstack/dws/v1/cluster/requests.go
> feat(Dws): upgrade create API, remove tags

- openstack/ecs/v1/cloudservers/requests.go
> feat(ecs): support Description in ecs v1 CreateOpts

- openstack/rms/v1/policyassignments/requests.go
- openstack/rms/v1/policyassignments/results.go
- openstack/rms/v1/policyassignments/urls.go
Add new sdk support for RMS service.
```release-note
```
> feat(rms/policy): add new policy assignment sdk

- openstack/dms/v1/instances/requests.go
> feat(dms): support tags in dms v1 CreateOpts

- openstack/autoscaling/v1/configurations/results.go
AS configuration result fix Extract label.
```release-note
```
> fix: as configuration result fix Extract

- openstack/identity/v3.0/security/requests.go
- openstack/identity/v3.0/security/results.go
- openstack/identity/v3.0/security/urls.go
currently, the security package includes two APIs:
- [Modifying the Password Policy](https://support.huaweicloud.com/intl/en-us/api-iam/iam_17_0003.html)
- [Querying the Password Policy](https://support.huaweicloud.com/intl/en-us/api-iam/iam_17_0004.html)
```release-note
```
> feat(iam): add security policy package

- pagination/http.go
add page request ok code
```release-note
```
> fix: add page request ok code

- openstack/waf_hw/v1/premium_domains/requests.go
waf dedicated domain support parameter `Plag`
```release-note
```
> feat: waf dedicated domain request add Flag

- openstack/nat/v2/snats/requests.go
- openstack/nat/v2/snats/results.go
- openstack/nat/v2/snats/urls.go
Copy and move the snat sdk to new directory.
```release-note
1. copy and move the snat sdk to new directory (/nat/v2).
```
> refactor(snat/rule): copy and move the snat sdk to new dir

- openstack/nat/v2/dnats/requests.go
- openstack/nat/v2/dnats/results.go
- openstack/nat/v2/dnats/urls.go
add new dnat sdk support
```release-note
```
> feat(dnat/rule): add new dnat sdk support

- openstack/fgs/v2/function/requests.go
> fix(fgs/function): add param when updating function created by mirror

- openstack/dms/v2/kafka/instances/requests.go
kafka instance support prepaid
kafka instance support prepaid
```release-note
```
> kafka instance  support prepaid

- openstack/elb/v2/loadbalancers/results.go
lb add public ip
```release-note
lb add public ip
```
> lb add public ip

- openstack/nat/v3/gateways/requests.go
- openstack/nat/v3/gateways/results.go
- openstack/nat/v3/gateways/urls.go
add new private nat gateway sdk support.
```release-note
1. add new private nat gateway sdk.
```
> feat(nat/gateway): add new private nat gateway sdk

- openstack/dns/v2/recordsets/results.go
- openstack/dns/v2/zones/requests.go
- openstack/dns/v2/zones/results.go
Fix dns sdk. 
- (1)Add missing field.
- (2)Mark `Deprecated` to invalid field.
```release-note
```
> fix: dns sdk fix

- openstack/cce/v3/nodepools/requests.go
- openstack/cce/v3/nodepools/results.go
> feat(cce): support CustomSecurityGroups in node pool

- openstack/common/tags/requests.go
- openstack/common/tags/results.go
- openstack/common/tags/urls.go
Add delete tag function, this func use `DELETE` type.
```release-note
```
> feat: add delete tag with key

- openstack/nat/v3/transitips/requests.go
- openstack/nat/v3/transitips/results.go
- openstack/nat/v3/transitips/urls.go
New sdk supported: transit IP for private NAT
```release-note
1. add new sdk support
```
> feat(nat/transitip): add new sdk support

- openstack/nat/v3/dnats/requests.go
- openstack/nat/v3/dnats/results.go
- openstack/nat/v3/dnats/urls.go
> feat(nat/dnat): add new sdk support

- openstack/nat/v3/snats/requests.go
- openstack/nat/v3/snats/results.go
- openstack/nat/v3/snats/urls.go
> feat(nat/snat): add new private snat sdk support

- openstack/ims/v1/imagecopy/requests.go
- openstack/ims/v1/imagecopy/results.go
- openstack/ims/v1/imagecopy/urls.go
add ims image copy
```release-note
```
> add ims image copy

- openstack/apigw/dedicated/v2/instances/requests.go
- openstack/apigw/dedicated/v2/instances/results.go
- openstack/apigw/dedicated/v2/instances/urls.go
> feat(apig/instance): support feature function

- openstack/apigw/dedicated/v2/acls/requests.go
- openstack/apigw/dedicated/v2/acls/results.go
- openstack/apigw/dedicated/v2/acls/urls.go
new sdk support: ACL policy.
```release-note
```
> faet(apig/acl): add new acl policy sdk support

- openstack/fgs/v2/function/requests.go
- openstack/fgs/v2/function/results.go
- openstack/fgs/v2/function/urls.go
```release-note
1. support async invoke functions.
```
> feat(fgs/async): add async invoke functions

- openstack/apigw/dedicated/v2/acls/requests.go
- openstack/apigw/dedicated/v2/acls/results.go
add new function to query acl list
```release-note
1.add new function to query acl list
```
> feat(apig/acl): add new function to query acl list

- openstack/waf_hw/v1/whiteblackip_rules/requests.go
- openstack/waf_hw/v1/whiteblackip_rules/results.go
waf whiteblackip support name and address group id
```release-note
```
> fix: waf whiteblackip support name and address group id

- openstack/mrs/v2/clusters/requests.go
> feat: support component_configs when creating MRS cluster

- openstack/rds/v3/instances/requests.go
- openstack/rds/v3/instances/results.go
- openstack/rds/v3/instances/urls.go
> feat(rds): add parameters support

- openstack/apigw/dedicated/v2/signs/requests.go
- openstack/apigw/dedicated/v2/signs/results.go
- openstack/apigw/dedicated/v2/signs/urls.go
1. add new signature sdk support
```release-note
```
> feat(apig/signature): add new signature sdk support

- openstack/dds/v3/instances/requests.go
dds instance support template
```release-note
```
> dds instance support template

- openstack/autoscaling/v1/instances/requests.go
- openstack/autoscaling/v1/instances/results.go
> feat(as): support appending a new instance in standby mode

- openstack/identity/v3.0/eps_permissions/requests.go
- openstack/identity/v3.0/eps_permissions/results.go
- openstack/identity/v3.0/eps_permissions/urls.go
> feat(iam): add v3.0 permissions for eps authorization

- openstack/dli/v1/queues/requests.go
Fix dli query list query builder.
```release-note
```
> fix(DLI): fix dli query list query builder

- openstack/identity/v3/roles/requests.go
- openstack/identity/v3/roles/results.go
> feat(iam/role): add CheckAllResourcesPermission func

- openstack/rds/v3/instances/requests.go
- openstack/rds/v3/instances/results.go
- openstack/rds/v3/instances/urls.go
> feat(rds): add reboot instance support

- openstack/sfs_turbo/v1/shares/requests.go
- openstack/sfs_turbo/v1/shares/results.go
refactor the `createOpts` structure and support a `BssParam` structure.
```release-note
```
> refactor(sfs/turbo): support prepaid function

- openstack/networking/v2/peerings/requests.go
- openstack/networking/v2/peerings/results.go
- openstack/networking/v2/peerings/testing/requests_test.go
```bash
$ go test -v ./
=== RUN   TestListVpcPeerings
--- PASS: TestListVpcPeerings (0.00s)
=== RUN   TestCreateVpcPeeringConnection
--- PASS: TestCreateVpcPeeringConnection (0.00s)
=== RUN   TestUpdateVpcPeeringConnection
--- PASS: TestUpdateVpcPeeringConnection (0.00s)
=== RUN   TestDeleteVpcPeeringConnection
--- PASS: TestDeleteVpcPeeringConnection (0.00s)
=== RUN   TestAcceptVpcPeering
--- PASS: TestAcceptVpcPeering (0.00s)
=== RUN   TestRejectVpcPeering
--- PASS: TestRejectVpcPeering (0.00s)
PASS
ok      github.com/chnsz/golangsdk/openstack/networking/v2/peerings/testing     0.016s
``` …
> feat: support create and update the description of vpc peering

- openstack/cbr/v3/backups/requests.go
- openstack/cbr/v3/backups/results.go
- openstack/cbr/v3/backups/urls.go
Support a new sdk to encoding provider codes.
```release-note
1. Add new backup sdk support.
```
> feat(cbr/backup): add new backup sdk support

- openstack/cce/v3/clusters/results.go
> feat(cce): support cidrs in cce cluster

- openstack/apigw/dedicated/v2/plugins/requests.go
- openstack/apigw/dedicated/v2/plugins/results.go
- openstack/apigw/dedicated/v2/plugins/urls.go
> feat(apig/plugin): add new resource support

- openstack/vpcep/v1/endpoints/requests.go
- openstack/vpcep/v1/endpoints/results.go
- openstack/vpcep/v1/services/requests.go
- openstack/vpcep/v1/services/results.go
vpcep support description
```release-note
```
> fix(VPCEP): vpcep support description

- openstack/ims/v2/cloudimages/requests.go
- openstack/ims/v2/cloudimages/results.go
- openstack/ims/v2/cloudimages/urls.go
ims support whole image
```release-note
ims support whole image
```
> feat(IMS): ims support whole image

- openstack/rds/v3/instances/requests.go
- openstack/rds/v3/instances/results.go
- openstack/rds/v3/instances/urls.go
Support automatic expansion functions.
- EnableAutoExpand
- DisableAutoExpand
- GetAutoExpand
```release-note
1. support automatic expansion functions.
```
> feat(rds/instance): support automatic expansion functions

- openstack/rds/v3/instances/requests.go
rds instance creation supports case-sensitive table names
```release-note
```
> rds support lower case table names

- openstack/modelarts/v1/notebook/results.go
refactor `if-else` logic and update the related description.
```release-note
1. update the 'if-else' logic and the description
```
> fix(notebook): Update the 'if-else' logic and the description

- openstack/geminidb/v3/instances/requests.go
- openstack/geminidb/v3/instances/results.go
- openstack/geminidb/v3/instances/urls.go
add param to gaussdb redis instance
```release-note
```
> add param to gaussdb redis instance

- openstack/cce/v3/addons/requests.go
- openstack/cce/v3/addons/results.go
> feat(cce): support updating version and values in addon

- openstack/ecs/v1/cloudservers/requests.go
- openstack/ecs/v1/cloudservers/results.go
fix ecs list pagination
```release-note
```
> fix(ECS): fix ecs list pagination

- openstack/vpcep/v1/endpoints/requests.go
- openstack/vpcep/v1/endpoints/results.go
vpcep endpoint add update function
```release-note
```
> fix(VPCEP): vpcep endpoint add update function

- openstack/networking/v1/subnets/requests.go
> feat(vpc/subnet): make extra_dhcp_opts.value a pointer

- openstack/identity/v3/agency/requests.go
- openstack/identity/v3/agency/results.go
> fix(iam/agency): update the type of Duration to interface

- openstack/dms/v2/rabbitmq/instances/requests.go
- openstack/dms/v2/rabbitmq/instances/results.go
- openstack/dms/v2/rabbitmq/instances/urls.go
rabbitmq support prepaid
```release-note
```
> rabbitmq support prepaid

- openstack/identity/v3/agency/requests.go
- openstack/identity/v3/agency/results.go
- openstack/identity/v3/agency/urls.go
> feat(iam/agency): support attach or detach inherited_to_projects roles

- openstack/smn/v2/topics/requests.go
- openstack/smn/v2/topics/results.go
- openstack/smn/v2/topics/urls.go
> feat(smn): support policies in topics

- openstack/cce/v3/clusters/requests.go
- openstack/cce/v3/clusters/results.go
> feat(cce/cluster): support subnets in eni and updating eni

- openstack/ims/v2/cloudimages/requests.go
- openstack/ims/v2/cloudimages/results.go
- openstack/ims/v2/cloudimages/urls.go
> feat(IMS): ims support update attribute

- openstack/cce/v3/clusters/requests.go
- openstack/cce/v3/clusters/results.go
**What this PR does / why we need it**: add custom san field in CCE cluster spec
```release-note
```
> feat(cce) add custom san field

- openstack/cbr/v3/vaults/requests.go
- openstack/cbr/v3/vaults/results.go
- openstack/cbr/v3/vaults/testing/fixtures.go
- openstack/cbr/v3/vaults/testing/requests_test.go
update binding structure and related tests
- support `destination_vault_id` and `policy_ids`
- update related acc tests
```release-note
go test -v -run=Test
=== RUN   TestCreateV3VaultsMarshall
--- PASS: TestCreateV3VaultsMarshall (0.00s)
=== RUN   TestCreateV3Vault
--- PASS: TestCreateV3Vault (0.00s)
=== RUN   TestGetV3Vault
--- PASS: TestGetV3Vault (0.00s)
=== RUN   TestUpdateV3Vault
--- PASS: TestUpdateV3Vault (0.00s)
=== RUN   TestDeleteV3Vault
--- PASS: TestDeleteV3Vault (0.00s)
=== RUN   TestListV3Vault
--- PASS: TestListV3Vault …
```
> refactor(cbr): update binding structure and related tests

- openstack/dms/v2/rabbitmq/instances/results.go
> feat(DMS): rabbitmq instance response support task

- openstack/cce/v3/clusters/requests.go
> feat(cce/cluster): support updating security group in cluster

- openstack/identity/v3/roles/requests.go
- openstack/identity/v3/roles/results.go
> fix(iam/role): update pager from Linked to PageSize

- openstack/taurusdb/v3/sqlfilter/requests.go
- openstack/taurusdb/v3/sqlfilter/results.go
- openstack/taurusdb/v3/sqlfilter/urls.go
gaussdb instance support sql filter
```release-note
gaussdb instance support sql filter
```
> feat(GaussDB): gaussdb instance support sql filter

- openstack/cbr/v3/policies/requests.go
- openstack/cbr/v3/vaults/requests.go
- openstack/cbr/v3/vaults/results.go
- openstack/cbr/v3/vaults/testing/fixtures.go
Support some parameters:
- backup_name_prefix (only used to create vault)
- demand_billing (only used to create vault)
- smn_notify
- threshold
- full_back_interval
```release-note
1. support new parameters
```
> feat(cbr): support new parameters

- openstack/identity/v3/roles/requests.go
- openstack/identity/v3/roles/results.go
> Revert "fix(iam/role): update pager from Linked to PageSize"

- openstack/sdrs/v1/drill/requests.go
remove sdrs drill vpc required
```release-note
```
> fix(SDRS): remove sdrs drill vpc required

- openstack/client.go
> chore: remove unused service client

- openstack/client.go
> chore: update the error message when failed to get the project ID

- openstack/fgs/v2/function/requests.go
- openstack/fgs/v2/function/urls.go
The API has been supported for max instance number update.
```release-note
1. support new method to update the max instance number.
```
> feat(fgs/function): add new method to update max instance number

- openstack/fgs/v2/function/requests.go
- openstack/fgs/v2/function/urls.go
Support two functions to manage tags
```release-note
1. support two functions to manage tags.
```
> feat(fgs/function): support two functions to manage tags

- openstack/er/v3/instances/requests.go
- openstack/er/v3/instances/results.go
- openstack/er/v3/instances/urls.go
Support new sdk (method) to query (filter) ER instance list.
```release-note
1. support new sdk (method) to query (filter) ER instance list.
```
> feat(er/instance): support list method to query instances

- openstack/er/v3/instances/results.go
The response strucutre miss a parameter: asn
```release-note
1. append a parameter names asn.
```
> chore(er/instance): append a parameter names asn

- pagination/list_all.go
List all pages add default header, cause some API requires `Content-Type` need to be set to "application/json;charset=utf8"
```release-note
```
> fix: list all pages add default header

- openstack/dcs/v2/instances/requests.go
dcs instance support template and update rename commands
```release-note
```
> dcs instance support template and update rename commands

- openstack/apigw/shared/v1/environments/requests.go
- openstack/apigw/shared/v1/environments/results.go
- openstack/apigw/shared/v1/environments/urls.go
Add APIG enironment shared  CRUD methods
```release-note
```
> Add APIG shared environment CRUD methods

- openstack/waf/v1/clouds/requests.go
- openstack/waf/v1/clouds/urls.go
add cloud waf post paid function
```release-note
```
> feat: add cloud waf post paid function

- openstack/apigw/dedicated/v2/certificates/requests.go
- openstack/apigw/dedicated/v2/certificates/results.go
- openstack/apigw/dedicated/v2/certificates/urls.go
Support a new SSL certificate sdk for APIG service.
- CRUD methods both are supported.
```release-note
1. support new ssl certificate sdk.
```
> feat(apig/cert): support new ssl certificate sdk

- openstack/elb/v3/l7policies/requests.go
- openstack/elb/v3/l7policies/results.go
elb policy add params
```release-note
elb policy add params
```
> feat(ELB): elb policy add params

- openstack/er/v3/attachments/requests.go
- openstack/er/v3/attachments/results.go
- openstack/er/v3/attachments/urls.go
add a new attachment sdk and support a list method.
```release-note
```
> feat(er/attachment): support new attachment sdk

- openstack/identity/v3.0/security/requests.go
- openstack/identity/v3.0/security/results.go
- openstack/identity/v3.0/security/urls.go
> feat(iam): support protection policy

- openstack/evs/v2/cloudvolumes/requests.go
- openstack/evs/v2/cloudvolumes/results.go
EVS add new parameters iops and throughput
```release-note
```
> fix: EVS add new parameters iops and throughput

- openstack/rds/v3/instances/requests.go
> fix(RDS): rds support restore

- openstack/fgs/v2/aliases/requests.go
- openstack/fgs/v2/aliases/results.go
- openstack/fgs/v2/aliases/urls.go
Support new aliases management sdk.
```release-note
```
> feat(fgs/alias): support new aliases management sdk

- openstack/sfs_turbo/v1/shares/requests.go
- openstack/sfs_turbo/v1/shares/results.go
- SFS Turbo add HPC share type file systems.
```release-note
```
> feat: SFS Turbo add HPC share type file systems.

- openstack/elb/v3/loadbalancers/requests.go
- openstack/elb/v3/loadbalancers/results.go
elb loadbalancer add params
```release-note
```
> feat(ELB): elb loadbalancer add params

- openstack/elb/v3/loadbalancers/requests.go
fix elb loadbalancer param
```release-note
```
> fix(ELB): fix elb loadbalancer param

- openstack/elb/v3/listeners/requests.go
- openstack/elb/v3/listeners/results.go
elb listener add params  protection_status and protection_reason
```release-note
```
> feat(ELB): elb listener add params

- openstack/networking/v2/bandwidths/requests.go
- openstack/networking/v2/bandwidths/results.go
- openstack/networking/v2/bandwidths/urls.go
https://support.huaweicloud.com/api-eip/ChangeBandwidthToPeriod.html
```release-note
```
> feat(bandwidth): add change to period API

- openstack/networking/v2/bandwidths/requests.go
- openstack/networking/v2/bandwidths/results.go
> chore(bandwidth): merge the response of Update method

- openstack/blockstorage/v2/volumes/requests.go
- openstack/blockstorage/v2/volumes/results.go
- openstack/evs/v2/cloudvolumes/results.go
> feat: add iops and throughput for Cinder API

- openstack/elb/v3/monitors/requests.go
- openstack/elb/v3/monitors/results.go
elb monitor add params
```release-note
```
> feat(ELB): elb monitor add params

- openstack/elb/v3/pools/requests.go
- openstack/elb/v3/pools/results.go
> feat(ELB): elb pool add params

- openstack/elb/v3/l7policies/requests.go
- openstack/elb/v3/l7policies/results.go
elb l7rule add params
```release-note
```
> feat(ELB):  elb l7rule add params

- openstack/ecs/v1/cloudservers/requests.go
> feat(ecs): add iops and throughput to volume

- openstack/cce/v3/nodes/results.go
> feat(cce/node): support dss in the volumes

- openstack/cce/v3/nodes/results.go
> feat(cce): support extension nics and InitializedConditions in the node

- errors.go
- provider_client.go
> enhance: add request id in error string

- openstack/mrs/v1/cluster/results.go
- openstack/mrs/v2/clusters/requests.go
> feat(MRS): support bootstrap script

- openstack/identity/v3.0/users/requests.go
- openstack/identity/v3.0/users/results.go
> feat(iam): support external identity id for IAM user

- openstack/rds/v3/instances/requests.go
- openstack/rds/v3/instances/results.go
- openstack/rds/v3/instances/urls.go
rds instance add params
```release-note
```
> feat(RDS): rds instance add params

- openstack/identity/v3.0/users/requests.go
> fix(iam/user): support celar description in UpdateOpts

- openstack/lts/huawei/loggroups/requests.go
- openstack/lts/huawei/loggroups/results.go
- openstack/lts/huawei/logstreams/requests.go
- openstack/lts/huawei/logstreams/results.go
> feat(lts): support tags in log group and stream

- openstack/apigw/dedicated/v2/appauths/requests.go
- openstack/apigw/dedicated/v2/appauths/results.go
- openstack/apigw/dedicated/v2/appauths/urls.go
support new sdk to develope application authorization resource. 
```release-note
1. support app authorization sdk.
```
> feat(apig): support app authorization sdk

- openstack/cce/v3/clusters/requests.go
- openstack/cce/v3/clusters/results.go
> feat(cce): update sdk of cluster

- openstack/rds/v3/securities/requests.go
rds securitites support update data ip
```release-note
```
> feat(RDS): rds securitites support update data ip

- openstack/cce/v3/nodes/requests.go
> feat(cce): support InitializedConditions and Storage in AddNodeSpec

- openstack/waf_hw/v1/policies/requests.go
- openstack/waf_hw/v1/policies/results.go
add new function to query all pages WAF policies
```release-note
```
> fix(WAF): add new function to query all pages WAF policies

- openstack/eg/v1/source/custom/requests.go
- openstack/eg/v1/source/custom/results.go
- openstack/eg/v1/source/custom/urls.go
For EventGrid service, support some methods that used to develop resources (custom event source).
- Create
- Get
- List
- Update
- Delete
```release-note
1. support new sdk for custom event source.
```
> feat(eg): support new sdk for custom event source

- openstack/rds/v3/instances/requests.go
change rds instance password to not required
```release-note
```
> fix(RDS): change rds instance password to opional

- openstack/ecs/v1/cloudservers/requests.go
- openstack/ecs/v1/cloudservers/results.go
- openstack/ecs/v1/cloudservers/urls.go
> feat(ecs): add metadata SDK support

- openstack/cce/v3/addons/requests.go
- openstack/cce/v3/addons/urls.go
> refactor(cce/addon): add updateURL func

- openstack/eg/v1/channel/custom/requests.go
- openstack/eg/v1/channel/custom/results.go
- openstack/eg/v1/channel/custom/urls.go
support custom channel sdk for EG service.
```release-note
1. add new sdk support for EG service.
```
> feat(eg/channel): add new sdk support

- openstack/workspace/v2/desktops/requests.go
- openstack/workspace/v2/desktops/results.go
add enterprise project id field
```release-note
```
> feat(workspace): add enterprise project id field

- openstack/elb/v3/listeners/requests.go
- openstack/elb/v3/listeners/urls.go
- openstack/elb/v3/loadbalancers/requests.go
- openstack/elb/v3/loadbalancers/urls.go
elb loadbalancer and listener support force delete
```release-note
```
> feat(ELB): elb loadbalancer and listener support force delete

- openstack/koogallery/v1/assets/requests.go
- openstack/koogallery/v1/assets/results.go
- openstack/koogallery/v1/assets/urls.go
> feat(koogallery): add koogallery assets support

- openstack/koogallery/v1/assets/urls.go
> fix(koogallery): use new url

- openstack/fgs/v2/function/requests.go
> feat(fgs): add log config support

- openstack/eg/v1/subscriptions/requests.go
- openstack/eg/v1/subscriptions/results.go
- openstack/eg/v1/subscriptions/urls.go
Add new subscription sdk support.
```release-note
1. support new subscription sdk for EG service.
```
> feat(eg/subscription): add new sdk support

- openstack/fgs/v2/function/requests.go
> fix(fgs): fix LogConfig parameter type

- openstack/apigw/dedicated/v2/channels/requests.go
support two parameters:
- label_key
- label_value
```release-note
```
> chore(apig/channel): support new params for microservice cfg

- openstack/cce/v3/clusters/requests.go
- openstack/cce/v3/clusters/urls.go
> feat(cce): support updating tags in cluster

- openstack/smn/v2/subscriptions/requests.go
> feat(smn): support extension in subscriptions

- openstack/tms/v1/resourcetags/requests.go
- openstack/tms/v1/resourcetags/results.go
- openstack/tms/v1/resourcetags/urls.go
Add new SDK that used to manage resource tags in batch.
```release-note
1. support new sdk to manage tags in batch.
```
> feat(tms/tags): support new sdk to manage tags in batch

- openstack/waf_hw/v1/datamasking_rules/results.go
waf rule data masking result struct add fields.
- add three new fields in waf rule data masking result struct.
```release-note
```
> fix(WAF): waf rule data masking result struct add fields

- openstack/tms/v1/providers/requests.go
- openstack/tms/v1/providers/results.go
- openstack/tms/v1/providers/urls.go
TMS resource tags management need a data source to query supported resources (providers) information.
```release-note
1. add new data source SDK used to query tags supported resources (providers) information.
```
> feat(tms/resources): add data source to query resources info

- openstack/dcs/v2/instances/requests.go
- openstack/dcs/v2/instances/results.go
- openstack/dcs/v2/instances/urls.go
dcs instance support parameters
```release-note
```
> feat(DCS): dcs instance support parameters

- openstack/cbr/v3/checkpoints/requests.go
- openstack/cbr/v3/checkpoints/results.go
- openstack/cbr/v3/checkpoints/urls.go
support new SDK for CBR service.
we can using the APIs of checkpoint and backup to back up resources.
```release-note
1. add checkpoint sdk support.
```
> feat(cbr/checkpoint): add new sdk support

- openstack/ecs/v1/cloudservers/requests.go
the schema will use the field
```release-note
```
> feat(ECS): add dss_pool_id related struct field.

- openstack/waf/v1/certificates/requests.go
- openstack/waf/v1/certificates/results.go
waf certificate fix struct fields
- update request body add `Content` and `Key`.
- detail response body add `Content` and `Key`, and fix `ExpireTime` json field.
```release-note
```
> fix(WAF): waf certificate fix struct fields

- openstack/smn/v2/logtank/requests.go
- openstack/smn/v2/logtank/results.go
- openstack/smn/v2/logtank/urls.go
Add CURD SDK for SMN logtank managed
doc:
https://support.huaweicloud.com/api-smn/CreateLogtank.html
https://support.huaweicloud.com/api-smn/UpdateLogtank.html
https://support.huaweicloud.com/api-smn/ListLogtank.html
https://support.huaweicloud.com/api-smn/DeleteLogtank.html
> feat(smn): Add SDK for SMN logtank managed

- openstack/elb/v3/listeners/requests.go
- openstack/elb/v3/loadbalancers/requests.go
- openstack/elb/v3/pools/requests.go
fix elb listener and pool params
```release-note
```
> fix(ELB): fix elb params

- openstack/vpcep/v1/services/requests.go
- openstack/vpcep/v1/services/results.go
vpcep service add new struct field `EnablePolicy`
```release-note
```
> fix(VPCEP): vpcep service add new struct field

- openstack/cbr/v3/vaults/requests.go
- openstack/cbr/v3/vaults/results.go
During the API release, a new parameter 'is_multi_az' support and need to append to the CBR vault SDK.
```release-note
1. add new parameter is_multi_az.
```
> feat(cbr/vault): add new parameter is_multi_az

- openstack/identity/v3/agency/requests.go
- openstack/identity/v3/agency/results.go
update sdk for data source identity agencies.
```release-note
```
> feat(iam): update sdk for data source identity agencies

- openstack/apigw/dedicated/v2/endpoints/requests.go
- openstack/apigw/dedicated/v2/endpoints/results.go
- openstack/apigw/dedicated/v2/endpoints/urls.go
add endpoint service permissions sdk support
```release-note
```
> feat(apig): add endpoint service permissions sdk support

- openstack/eg/v1/source/custom/requests.go
- openstack/eg/v1/source/custom/results.go
The `detail` parameter is required if the event source of the type **ROCKETMQ** or type **RABBITMQ** is created.
```release-note
1. support new parameter detail
```
> feat(eg/source): support new parameter detail

- openstack/cdn/v1/domains/requests.go
fix struct field for cdn resource
```release-note
```
> fix(cdn): fix struct field to support standby domain

- openstack/vpn/v5/customer_gateways/requests.go
- openstack/vpn/v5/customer_gateways/results.go
- openstack/vpn/v5/customer_gateways/urls.go
add sdk for datasource vpn_customer_gateway to search resource
```release-note
api: https://support.huaweicloud.com/api-vpn/vpn_api_0023.html
```
> feat(vpn): add sdk for datasource vpn_customer_gateway

- openstack/autoscaling/v1/scheduledtasks/requests.go
- openstack/autoscaling/v1/scheduledtasks/results.go
- openstack/autoscaling/v1/scheduledtasks/urls.go
add AS planned task sdk support
```release-note
add AS planned task sdk support
```
> feat(as): add planned task sdk support

- openstack/vpcep/v1/services/requests.go
- openstack/vpcep/v1/services/results.go
vpcep service complete parameters
```release-note
```
> feat(Vpcep): vpcep service add PermissionType field

- openstack/opengauss/v3/instances/requests.go
remove open gauss request ok code
```release-note
remove open gauss request ok code
```
> fix(GaussDB): remove open gauss request ok code

- openstack/autoscaling/v1/scheduledtasks/requests.go
change the parameter type of the instanceNumber structure from int to point.
```release-note
fix planned task parameters type
```
> fix(as): fix planned task parameters type

- openstack/vpcep/v1/services/requests.go
- openstack/vpcep/v1/services/results.go
public VPC endpoint services datasource add pagination
```release-note
```
> feat(Vpcep): public VPC endpoint services datasource add pagination

- .github/labeler.yml
- .github/workflows/pull-request.yml
> chore(ci): add PR Labeler and Validate workflow

- openstack/eps/v1/enterpriseprojects/requests.go
add new request parameter[type, sort_key, sort_dir]
```add new request parameter[type, sort_key, sort_dir]
```
> feat(eps): add new request parameter in ListOpts

- openstack/vpcep/v1/services/requests.go
- openstack/vpcep/v1/services/results.go
vpcep services connections and whitelist add pagination
```release-note
```
> feat(Vpcep): vpcep services connections and whitelist add pagination

- openstack/vpn/v5/connections/requests.go
- openstack/vpn/v5/connections/results.go
- openstack/vpn/v5/connections/urls.go
**What this PR does / why we need it**:feat(vpn): add vpn_connections sdk
```release-note
```
> feat(vpn): add vpn_connections sdk

- openstack/dns/v2/associate/requests.go
- openstack/dns/v2/associate/results.go
- openstack/dns/v2/associate/urls.go
Add dns resolver rule associate router sdk
> feat(dns): Add dns resolver rule associate router sdk

- openstack/waf_hw/v1/domains/requests.go
- openstack/waf_hw/v1/domains/results.go
> feat(waf): Complete the missing parameters in the waf domain

- openstack/dns/v2/resolverrule/requests.go
- openstack/dns/v2/resolverrule/results.go
- openstack/dns/v2/resolverrule/urls.go
> feat(dns): Add dns resolver rule sdk

- openstack/apigw/dedicated/v2/apis/requests.go
The conditions structure policy type supports new enumeration values and new parameters
```release-note
conditions struct support new parameters
```
> feat(apig/api): conditions struct support new parameters

- openstack/sfs_turbo/v1/shares/requests.go
- openstack/sfs_turbo/v1/shares/results.go
sfsTurbo resource support edit name field
```release-note
```
> feat(sfsTurbo): sfsTurbo resource support edit name field

- openstack/workspace/v2/accesspolicies/requests.go
- openstack/workspace/v2/accesspolicies/results.go
- openstack/workspace/v2/accesspolicies/urls.go
Support a new resource sdk for workspace access policy.
```release-note
1. support the access policy sdk
```
> feat(workspace): support the access policy sdk

- openstack/workspace/v2/desktops/requests.go
- openstack/workspace/v2/desktops/results.go
- openstack/workspace/v2/desktops/urls.go
The desktop SDK support a new method to modify the image configuration and os type.
```release-note
1. desktop sdk support rebuild method
```
> feat(workspace): desktop sdk support rebuild method

- openstack/workspace/v2/terminals/requests.go
- openstack/workspace/v2/terminals/results.go
- openstack/workspace/v2/terminals/urls.go
Support a new SDK for termimal bindings.
```release-note
1. support the new sdk for terminal bindings
```
> feat(workspace): support the new sdk for terminal bindings

- openstack/workspace/v2/policygroups/requests.go
- openstack/workspace/v2/policygroups/results.go
- openstack/workspace/v2/policygroups/urls.go
New SDK supported for workspace policy group.
```release-note
1. support the new sdk for policy group.
```
> feat(workspace): support the new sdk for policy group

- openstack/bss/v2/orders/requests.go
- openstack/bss/v2/orders/results.go
- openstack/bss/v2/orders/urls.go
bss support pay order
```release-note
```
> feat(BSS): bss add pay order

- openstack/dcs/v2/instances/requests.go
- openstack/dcs/v2/instances/results.go
- openstack/dcs/v2/instances/urls.go
dcs support prepaid resize
```release-note
```
> feat(DCS): dcs support prepaid resize

- openstack/sfs_turbo/v1/shares/requests.go
- openstack/sfs_turbo/v1/shares/results.go
sfs_turbo resource support edit security_group_id field
```release-note
```
> feat(sfsTurbo): sfs_turbo resource support edit security_group_id field

- openstack/waf_hw/v1/domains/requests.go
> fix(waf): fix fields type and add LbAlgorithm to UpdateOpts

- openstack/workspace/v2/groups/requests.go
- openstack/workspace/v2/groups/results.go
- openstack/workspace/v2/groups/urls.go
add user group sdk support
```release-note
add user group sdk support
```
> feat(workspace): add user group sdk support

- openstack/vpn/v5/connection_monitors/requests.go
- openstack/vpn/v5/connection_monitors/results.go
- openstack/vpn/v5/connection_monitors/urls.go
**What this PR does / why we need it**:add data_source_vpn_connection_health_checks
```release-note
```
> feat(vpn): add sdk of connection_monitors

- openstack/workspace/v2/desktops/requests.go
- openstack/workspace/v2/desktops/results.go
- openstack/workspace/v2/desktops/urls.go
support the new sdk for binding eip
```release-note
1.support the new sdk for binding eip
```
> feat(workspace): support the new sdk for binding eip

- openstack/elb/v3/loadbalancers/requests.go
- openstack/elb/v3/loadbalancers/urls.go
support availability zone modification for resource loadbalancer
```release-note
```
> feat(ELB): support availability zone modification for resource loadbalancer

- openstack/workspace/v2/desktops/requests.go
- openstack/workspace/v2/desktops/results.go
- openstack/workspace/v2/desktops/urls.go
The desktop sdk support update network.
```release-note
The desktop sdk support update network.
```
> feat(workspace): desktop sdk support update network

- openstack/workspace/v2/services/requests.go
- openstack/workspace/v2/services/results.go
- openstack/workspace/v2/services/urls.go
Support OPT authentication strategy
```release-note
Support OPT authentication strategy
```
> feat(workspace): Support OPT authentication strategy

- openstack/dayu/v1/connections/requests.go
- openstack/dayu/v1/connections/results.go
- openstack/dayu/v1/connections/urls.go
Add new data connection SDK support for DataArts Studio service.
```release-note
1. support data connection sdk
```
> feat(dataarts): support data connection sdk

- openstack/vpcep/v1/services/requests.go
- openstack/vpcep/v1/services/results.go
support to query the list of VPC endpoint services
> feat(VPCEP): support to query the list of VPC endpoint services

- openstack/rds/v3/instances/requests.go
- openstack/rds/v3/instances/results.go
rds intance support modify maintain window
```release-note
```
> feat(RDS): rds intance support modify maintain window

- openstack/autoscaling/v1/activitylogs/requests.go
- openstack/autoscaling/v1/activitylogs/results.go
- openstack/autoscaling/v1/activitylogs/urls.go
add AS activity logs datasource sdk support
```release-note
1. add AS activity logs datasource sdk support
```
> feat(as): add AS activity logs datasource sdk support

- openstack/cdm/v1/clusters/results.go
- openstack/cdm/v1/link/requests.go
> chore(cdm): update sdk for new params

- openstack/networking/v3/security/rules/requests.go
Add ID parameter to ListOpts structure.
```release-note
networking rules add new parameters support
```
> feat(networking): networking rules add new parameters support

- openstack/waf_hw/v1/domains/requests.go
- openstack/waf_hw/v1/domains/results.go
- openstack/waf_hw/v1/domains/urls.go
- add new SDK to update waf domain protect status
- This SDK has been verified.
```release-note
```
> feat(WAF): add new sdk to update waf domain protect status

- openstack/autoscaling/v1/policies/requests.go
- openstack/autoscaling/v1/policies/results.go
- openstack/autoscaling/v1/policies/urls.go
1. Add relevant structures and functions for the List method.
2. Add new parameters to action structures.
```release-note
1. add policies datasource sdk support
```
> feat(as): add policies datasource sdk support

- openstack/evs/v5/cloudvolumes/requests.go
- openstack/evs/v5/cloudvolumes/resullts.go
- openstack/evs/v5/cloudvolumes/urls.go
> fix(EVS): resource EVS supports updating QoS of cloudvolume

- openstack/dms/v2/kafka/instances/results.go
> feat(DMS): kafka instance result support task

- openstack/waf_hw/v1/domains/requests.go
+ Change the http request type for updating waf domain to **patch**， the background of some offices has been updated and the **put** method is no longer supported.
```release-note
```
> fix(WAF): change the http request type for updating waf domain to patch

- openstack/rds/v3/instances/requests.go
- openstack/rds/v3/instances/results.go
> feat(RDS): rds instance support modify replication mode

- openstack/cdm/v1/link/requests.go
> fix(cdm): fix bug in cdm link sdk

- openstack/rds/v3/instances/requests.go
- openstack/rds/v3/instances/results.go
> feat(RDS): rds instance support switch strategy

- openstack/nat/v3/gateways/results.go
add vpc_id attribute to the private nat gateway response body
```release-note
```
> chore(nat): add vpc_id attribute to the private nat gateway response body

- openstack/networking/v1/ports/requests.go
- openstack/networking/v1/ports/results.go
1.ports create request add paramter "ip_version"
2.modify UpdateOpts paramter to omitempty
3.add response  attribute “enable_efi” and "ipv6_bandwidth_id"
```release-note
```
> feat(VPC): update the requestbody and responsebody of ports

- openstack/fgs/v2/dependencies/requests.go
- openstack/fgs/v2/dependencies/results.go
- openstack/fgs/v2/dependencies/urls.go
Support some funtions to support the custom dependencies (with version information) management.
```release-note
1. Three funtions are supported for the custom dependencies (with version information) management.
```
> feat(fgs/depend): new functions for version dependencies

- openstack/rds/v3/instances/requests.go
- openstack/rds/v3/instances/results.go
> feat(RDS): rds instance support modify collation

- openstack/workspace/v2/desktops/requests.go
- openstack/workspace/v2/desktops/results.go
- openstack/workspace/v2/desktops/urls.go
Add power action function for the Workspace desktop.
API and console are support power action.
```release-note
1. The Workspace desktop support startup, shutdown, restart, hibernate action.
```
> feat(workspace): the desktop support power action

- openstack/networking/v1/ports/requests.go
1.update ports UpdateOpts paramter Name to no omitempty.
> feat(VPC): update the requestbody of ports

- openstack/dms/v2/kafka/instances/requests.go
- openstack/dms/v2/kafka/instances/results.go
- openstack/dms/v2/kafka/instances/urls.go
```release-note
reset password for kafka instance
```
> feat(DMS): reset password for kafka instance

- openstack/ecs/v1/cloudservers/requests.go
- openstack/ecs/v1/cloudservers/results.go
- openstack/ecs/v1/cloudservers/urls.go
1.add request and response parameter auto_terminate_time
2.add method UpdateAutoTerminateTime for update auto_terminate_time
> feat(ECS): ecs instance support auto terminate time

- openstack/networking/v1/ports/requests.go
1.remove ports updateOpts parameter's "omitempty"
> feat(VPC): update the request body of ports

- openstack/dms/v2/rabbitmq/instances/urls.go
modify flavor with new api
```release-note
modify flavor with new api
```
> feat(DMS): modify flavor with new api

- openstack/bms/v1/baremetalservers/requests.go
- openstack/bms/v1/baremetalservers/urls.go
feat(BMS): bms instance support edit nics
```release-note
1. Support edit nic attribute information when creating a BMS instance.
```
> feat(BMS): bms instance support edit nics

- openstack/workspace/v2/services/results.go
Modify field type to string.
```release-note
1. modify LockTime field type to string.
```
> chore(workspace/service): modify field type to string

- openstack/rds/v3/instances/requests.go
- openstack/rds/v3/instances/results.go
rds instance support update volume size in prepaid mode
```release-note
```
> feat(RDS): rds instance support update volume size in prepaid mode

- openstack/ecs/v1/cloudservers/requests.go
**What this PR does / why we need it**: modify update methods and add structural parameter
```release-note
```
> fix(ecs): modify update methods and add structural parameter

- openstack/networking/v1/bandwidths/results.go
Add attributes `created_at` and `updated_at` for bandwidth
> chore(eip): add attributes for bandwidth

- openstack/autoscaling/v1/policyexecutelogs/requests.go
- openstack/autoscaling/v1/policyexecutelogs/results.go
- openstack/autoscaling/v1/policyexecutelogs/urls.go
add query policy execute logs list sdk support
```release-note
add query policy execute logs list sdk support
```
> feat(as): add query policy execute logs list sdk support

- openstack/dms/v2/kafka/instances/requests.go
fix kafka instance params tag from required to omitempty
```release-note
```
> fix(Kafka): fix kafka instance param tag from required to omitempty

- openstack/bms/v1/baremetalservers/requests.go
- openstack/bms/v1/baremetalservers/results.go
- openstack/bms/v1/baremetalservers/urls.go
bms support edit metadata
```release-note
```
> feat(BMS): bms support edit metadata

- openstack/cdn/v1/domains/requests.go
- openstack/cdn/v1/domains/results.go
- openstack/cdn/v1/domains/urls.go
+ the source supports updating private buckets access
```release-note
```
> feat(CDN): the resource supports updating private buckets access

- openstack/networking/v1/eips/requests.go
- openstack/networking/v1/eips/results.go
- openstack/networking/v1/eips/urls.go
Add `changeToPeriod` function for updating `charging_mode` in `resource.huaweicloud_vpc_eip`
> chore(eip): add change to period for updating charging mode

- openstack/identity/v3/projects/requests.go
- openstack/identity/v3/projects/results.go
- openstack/identity/v3/projects/urls.go
Add `UpdatePorjectStatus` function in project for `resource.huaweicloud_identity_project`.
> chore(iam): add update status function in project

- openstack/cdn/v1/domains/results.go
+ add field ErrorResp to result struct to verify the situation when an error occurs but the API is passed
```release-note
```
> fix(CDN): add field ErrorResp to result struct

- openstack/networking/v3/eips/requests.go
- openstack/networking/v3/eips/results.go
- openstack/networking/v3/eips/urls.go
support `v3.showPublicip` api for `resource.huaweicloud_vpc_eip`
> chore(eip): support v3 showPublicip api in eip

- openstack/networking/v3/eips/urls.go
change v3 eip url, remove projectID.
> chore(eip): change v3 eip url

- openstack/apigw/dedicated/v2/instances/requests.go
- openstack/apigw/dedicated/v2/instances/results.go
- openstack/apigw/dedicated/v2/instances/urls.go
The dedicated instance support ingress EIP when **loadbalancer_provider** is set to **elb**.
```release-note
```
> feat(apig/instance): the 'elb' instance support ingress EIP

- openstack/networking/v3/eips/requests.go
- openstack/networking/v3/eips/results.go
- openstack/networking/v3/eips/urls.go
add `v3.listPublicip` for `data.huaweicloud_vpc_eips`.
> chore(eip): add v3 listPublicip for eip

- openstack/scm/v3/certificates/requests.go
modify certificate_chain to optional
modify certificate_chain to optional
> fix(ccm): modify certificate_chain to optional

- openstack/rds/v3/instances/requests.go
- openstack/rds/v3/instances/results.go
- openstack/rds/v3/instances/urls.go
rds instance support modify configuration
```release-note
```
> feat(RDS): rds instance support modify configuration

- openstack/dds/v3/instances/requests.go
API already support password-not-required options, so modify creating dds instance password to optional
```release-note
API already support password-not-required options, so modify creating dds instance password to optional
```
> feat(dds): modify creating dds instance password to optional

- openstack/identity/v3.0/users/requests.go
- openstack/identity/v3.0/users/results.go
- openstack/identity/v3.0/users/urls.go
Support login protect for `huaweicloud_identity_user`.
> feat(iam): support login protect for user

- openstack/dli/v1/queues/requests.go
- openstack/dli/v1/queues/results.go
- openstack/dli/v3/elasticresourcepool/requests.go
- openstack/dli/v3/elasticresourcepool/results.go
- openstack/dli/v3/elasticresourcepool/urls.go
The resource suppouts associating a queue with an elastic resource pool.
```release-note
```
> feat(dli): the resource supports associate elastic resource pool

- openstack/bms/v1/baremetalservers/requests.go
- openstack/bms/v1/baremetalservers/results.go
- openstack/bms/v1/baremetalservers/urls.go
add new API to support query BMS instance list
```release-note
```
> feat(BMS): add new API to support query BMS instance list

- openstack/dms/v2/kafka/instances/requests.go
- openstack/dms/v2/kafka/instances/results.go
- openstack/dms/v2/kafka/instances/urls.go
kafka supports paramters updated
```release-note
kafka supports paramters updated
```
> feat(Kafka): kafka supports paramters updated

- openstack/fgs/v2/function/requests.go
- openstack/fgs/v2/function/results.go
- openstack/fgs/v2/function/urls.go
The fgs service supports function reserved instance configuration.
```release-note
```
> feat(fgs): support function reserved instance configuration

- openstack/fgs/v2/function/requests.go
- openstack/fgs/v2/function/results.go
Support concurrent requests number for single function.
```release-note
1. add new parameter 'concurrent_num'.
```
> feat(fgs/function): support config concurrent requests number

- openstack/dcs/v2/instances/requests.go
- openstack/dcs/v2/instances/results.go
- openstack/dcs/v2/instances/urls.go
dcs supports ssl updated
```release-note
dcs supports ssl updated
```
> feat(DCS): dcs supports ssl updated

- openstack/cce/v3/clusters/requests.go
> feat(cce): support resizing cluster

- openstack/dds/v3/instances/requests.go
- openstack/dds/v3/instances/results.go
- openstack/dds/v3/instances/urls.go
support dds instance set backupPolicy and switch secondLevelMonitoring
```release-note
support dds instance set backup policy and switch second level monitoring
```
> feat(dds): support dds instance set backup policy and switch second level monitoring

- openstack/dds/v3/instances/requests.go
- openstack/dds/v3/instances/results.go
- openstack/dds/v3/instances/urls.go
…og status
support dds instance set description and availability zone and slow log status
```release-note
support dds instance set description and availability zone and slow log status
```
> feat(dds): support dds instance set description and availability zone and slow log status

- openstack/nat/v2/snats/requests.go
- openstack/nat/v2/snats/results.go
Public snat rule resource support global_eip_id parameter.
```release-note
```
> feat(nat): public snat rule resource support global_eip_id parameter

- openstack/kms/v1/keys/requests.go
- openstack/kms/v1/keys/results.go
add creation parameter origin to support creating import key
```release-note
```
> feat(kms): add creation parameter origin to support creating import key

- openstack/drs/v3/jobs/results.go
support tags in `huaweicloud_drs_job`
> feat(drs): support tags in job

- openstack/nat/v2/dnats/requests.go
- openstack/nat/v2/dnats/results.go
Public dnat rule resource support global_eip_id parameter.
```release-note
```
> feat(nat): public dnat rule resource support global_eip_id parameter

- openstack/fgs/v2/function/requests.go
- openstack/fgs/v2/function/results.go
The function supports GPU config.
```release-note
```
> feat(fgs/function): support gpu config in function

- openstack/mrs/v2/clusters/requests.go
- openstack/mrs/v2/clusters/results.go
cluster support prepaid.
cluster support prepaid.
```release-note
```
> feat(mrs): cluster support prepaid

- openstack/kms/v1/keys/requests.go
- openstack/kms/v1/keys/results.go
- openstack/kms/v1/keys/urls.go
kms support to manage key material of the external key
```release-note
1. kms support import key material for all external key.
2. kms support delete key material of the symmetric key.
```
> feat(kms): kms support to manage key material of the external key

- openstack/dcs/v2/instances/results.go
add attribute lanched_at
```release-note
add attribute lanched_at
```
> feat(DCS): add attribute lanched_at

- openstack/dds/v3/instances/requests.go
- openstack/dds/v3/instances/results.go
- openstack/dds/v3/instances/urls.go
fix dds instance method
```release-note
```
> fix(DDS): fix dds instance method

- openstack/cdn/v1/domains/requests.go
- openstack/cdn/v1/domains/results.go
- openstack/cdn/v1/domains/urls.go
add new sdk to query cdn domain detail
- The sdk `Get` is Deprecated.
```release-note
```
> feat(CDN): add new sdk to query cdn domain detail

- openstack/drs/v3/jobs/results.go
Support select objects in `huaweicloud_drs_job` and fix attributes type.
> feat(drs): support select objects in drs job and fix attributes type

- openstack/vpcep/v1/endpoints/requests.go
modify the error of the routetables parameter and add related usage instruction.
```release-note
```
> chore(vpcep): modify the error related to the routetables parameter 

- openstack/dli/v2/spark/resources/requests.go
- openstack/dli/v2/spark/resources/results.go
The DLI package supports no grouping feature.
```release-note
```
> chore(dli): the package supports no grouping feature

- openstack/drs/v3/jobs/requests.go
- openstack/drs/v3/jobs/results.go
Support `charging_mode` in job
> feat(drs): support charging mode in job

- openstack/kms/v1/keys/requests.go
- openstack/kms/v1/keys/results.go
kms key support keystore_id parameter
```release-note
1.Add keystore_id when create KMS key.
```
> feat(kms): kms key support keystore_id parameter

- openstack/dli/v3/tags/requests.go
- openstack/dli/v3/tags/urls.go
The dli package supports tags configuration.
```release-note
```
> feat(dli): the dli package supports tags configuration

- openstack/er/v3/associations/results.go
- openstack/er/v3/propagations/results.go
The list of propagations or associates supports pagination.
Modify lastmaker method logic  of propagations and associates.
```release-note
```
> chore(er): modify lastmaker method  of propagations and associates

- openstack/dcs/v2/instances/results.go
dcs adds new attributes
```release-note
dcs adds new attributes
```
> feat(DCS): add new attributes

- openstack/elb/v3/loadbalancers/requests.go
- openstack/elb/v3/loadbalancers/results.go
elb adds new attributes
```release-note
elb adds new attributes
```
> feat(ELB): add new attributes

- openstack/rds/v3/instances/requests.go
- openstack/rds/v3/instances/results.go
- openstack/rds/v3/instances/urls.go
rds instance support msdtc hosts
```release-note
```
> feat(RDS): rds instance support msdtc hosts

- openstack/rds/v3/configurations/results.go
rds configurations add attributes created and updated
```release-note
```
> feat(RDS): rds configurations add attributes created and updated

- openstack/drs/v3/jobs/requests.go
- openstack/drs/v3/jobs/results.go
- openstack/drs/v3/jobs/urls.go
Support to get progress in `huaweicloud_drs_job`
> feat(drs): support to get progress in job

- openstack/rds/v3/instances/requests.go
- openstack/rds/v3/instances/results.go
1. rds instance support startup and shutdown
2. replace some response with job response
```release-note
```
> feat(RDS): rds instance support startup and shutdown

- openstack/elb/v3/listeners/requests.go
- openstack/elb/v3/listeners/results.go
elb add new attributes
```release-note
add new attributes
```
> feat(ELB): listener add new attributes

- openstack/rds/v3/instances/requests.go
- openstack/rds/v3/instances/results.go
1. fix rds instance startup and shutdown
2. fix rds instance job response
```release-note
```
> fix(RDS): fix rds instance request and result

- openstack/cdn/v1/domains/requests.go
- openstack/cdn/v1/domains/urls.go
add new sdk to query cdn domain tags.
```release-note
```
> feat(CDN): add new sdk to query cdn domain tags

- .github/labeler.yml
- .github/workflows/prow-command.yml
- .github/workflows/prow-merge-on-lgtm.yml
- OWNERS
> ci: add prow robot

- openstack/drs/v3/jobs/results.go
fix attribute type for `alarm_notify`
> fix(drs): fix attribute type for alarm notify

- .github/workflows/prow-merge-on-lgtm.yml
> ci: update prow robot schedule

- openstack/elb/v3/pools/results.go
Fix persistence.type for `huaweicloud_elb_pool`
> fix(elb): fix persistence type for pool

- openstack/rds/v3/instances/requests.go
- openstack/rds/v3/instances/results.go
- openstack/rds/v3/instances/urls.go
1. rds instance support tde
2. fix update and get url
```release-note
```
> feat(RDS): rds instance support tde

- openstack/elb/v3/ipgroups/results.go
- openstack/elb/v3/l7policies/results.go
Add attrs for policy and ipgroup，including `created_at` and `updated_at`.
> feat(elb): add attrs for policy and ipgroup

- openstack/dli/v3/queues/requests.go
- openstack/dli/v3/queues/result.go
- openstack/dli/v3/queues/urls.go
The queue supports setting properities.
```release-note
```
> feat(dli): the queue supports setting properities

- openstack/elb/v3/listeners/requests.go
- openstack/elb/v3/listeners/results.go
Support new params for listener.
> feat(elb): support new params for listener

- openstack/elb/v2/loadbalancers/requests.go
- openstack/elb/v2/loadbalancers/results.go
- openstack/elb/v3/loadbalancers/requests.go
- openstack/elb/v3/loadbalancers/results.go
- openstack/elb/v3/loadbalancers/urls.go
Support new params for load balancer.
> feat(lb): support new params for load balancer

- openstack/rds/v3/instances/requests.go
rds instance support read write permissions
```release-note
```
> feat(RDS): rds instance support read write permissions

- openstack/dds/v3/instances/requests.go
- openstack/dds/v3/instances/results.go
- openstack/dds/v3/instances/urls.go
Support `replica_set_name` in instance.
> feat(dds): support to set replica set name in instance

- openstack/dds/v3/instances/requests.go
- openstack/dds/v3/instances/urls.go
> feat(dds): support restart in instance

- openstack/dds/v3/instances/requests.go
> fix(dds): fix name of target type

- openstack/dds/v3/flavors/requests.go
- openstack/dds/v3/flavors/results.go
1. add query param engine_version
2. add attributes az_status and engine_versions
```release-note
```
> feat(DDS): fix dds flavors

- openstack/rds/v3/instances/requests.go
- openstack/rds/v3/instances/results.go
rds instance support second level monitoring
```release-note
```
> feat(RDS): rds instance support second level monitoring

- openstack/nat/v2/gateways/requests.go
- openstack/nat/v2/gateways/results.go
The NAT gateway supports ngport_ip_address field.
```release-note
```
> feat(nat): the NAT gateway supports ngport_ip_address field

- openstack/fgs/v2/versions/requests.go
The create API has been support and we can manage function version as well.
```release-note
1. function supports create version
```
> feat(fgs/version): function supports create version

- openstack/rds/v3/instances/requests.go
rds instance support modify private dns name prefix
```release-note
```
> feat(RDS): rds instance support modify private dns name prefix

- openstack/apigw/dedicated/v2/environments/requests.go
- openstack/apigw/dedicated/v2/environments/results.go
Supports updating environment variable.
```release-note
```
> feat(apig): supports updating environment variable

- openstack/apigw/dedicated/v2/apigroups/requests.go
- openstack/apigw/dedicated/v2/apigroups/results.go
- openstack/apigw/dedicated/v2/apigroups/urls.go
The group supports modifying whether the APIs can be accessed through the debugging domain name.
```release-note
```
> feat(apig/group): supports debugging domain name access feature

- openstack/rds/v3/instances/requests.go
- openstack/rds/v3/instances/results.go
rds instance support slow log show original status
```release-note
```
> feat(RDS): rds instance support slow log show original status

- openstack/dds/v3/instances/requests.go
Support to add nodes for replica set instance.
> feat(dds): support to add nodes for replica set instance

- openstack/dds/v3/instances/requests.go
- openstack/dds/v3/instances/urls.go
Support to set maintenance window for instance
> feat(dds): support to set maintenance window for instance

- openstack/dds/v3/instances/requests.go
- openstack/dds/v3/instances/results.go
- openstack/dds/v3/instances/urls.go
Support setting balancer configuration in dds instance, and return charging_mode.
> feat(dds): support setting balancer configuration

- openstack/fgs/v2/dependencies/requests.go
- openstack/fgs/v2/dependencies/results.go
Change the paging method from `SinglePageBase` to `MarkerPageBase`.
```release-note
```
> chore(fgs): modify the paging method of dependent package versions

- openstack/dds/v3/instances/requests.go
- openstack/dds/v3/instances/urls.go
Support to set client network ranges. And fix the return of UpdateMaintenanceWindow for it has no return.
> feat(dds): support to set client network ranges

- openstack/fgs/v2/dependencies/results.go
add support to attributes for fgs
```release-note
```
> feat(fgs): add support to attributes for fgs

- openstack/apigw/dedicated/v2/apis/requests.go
- openstack/apigw/dedicated/v2/apis/results.go
Complete the 'id' parameter of the backend configuration.
```release-note
```
> feat(apig): add 'id' parameter related to backend details

- openstack/cci/v1/networks/requests.go
CCI network availability_zone from required to optional
```
CCI network availability_zone from required to optional
```
> feat(cci): CCI network availability_zone from required to optional

- openstack/ecs/v1/cloudservers/requests.go
> feat(ecs): support IP accurate match is ListOpts of instance

- openstack/fgs/v2/function/requests.go
- openstack/fgs/v2/function/results.go
add func_vpc and network_controller parameter.
```release-note
```
> feat(fgs): add func_vpc and network_controller parameter

- openstack/dms/v2/kafka/topics/requests.go
- openstack/dms/v2/kafka/topics/results.go
Add new params for kafka topic, including `configs` and `description`.
> feat(dms): add new params for kafka topic

- openstack/dc/v3/interfaces/results.go
fix DC virtual interface response fields
```release-note
```
> fix(DC): fix DC virtual interface response fields

- openstack/elb/v3/pools/requests.go
- openstack/elb/v3/pools/results.go
elb pool add param
```release-note
```
> feat(ELB): elb pool add param

- openstack/elb/v3/pools/requests.go
- openstack/elb/v3/pools/results.go
fix elb pool
```release-note
```
> fix(ELB): fix elb pool

- openstack/dns/v2/zones/requests.go
- openstack/dns/v2/zones/urls.go
The public zone supports setting status.
```release-note
```
> feat(dns/zone): public zone supports modifying status

- openstack/elb/v3/pools/requests.go
fix elb member param
```release-note
```
> fix(ELB): fix elb member param

- openstack/elb/v3/l7policies/requests.go
- openstack/elb/v3/l7policies/results.go
elb l7policy add params
```release-note
```
> feat(ELB): elb l7policy add params

- openstack/autoscaling/v1/groups/requests.go
- openstack/autoscaling/v1/groups/results.go
- AS group support new fields.
- Fix update parameter `IsDeletePublicip` from **bool** to ***bool**.
```release-note
```
> fix(AS): AS group support new fields.

- openstack/apigw/dedicated/v2/apis/requests.go
- openstack/apigw/dedicated/v2/apis/results.go
Support some parameters:
- func_info.alias_urn
- func_info.network_type
- func_info.req_protocol
- policy_functions.alias_urn
- policy_functions.network_type
- policy_functions.req_protocol
```release-note
1. new parameters are supported.
```
> feat(apig/api): new params are supported

- openstack/dms/v2/kafka/instances/requests.go
- openstack/dms/v2/kafka/instances/urls.go
Support to get task detail for kafka
> feat(dms): support to get task for kafka

- openstack/autoscaling/v1/lifecyclehooks/requests.go
- openstack/autoscaling/v1/lifecyclehooks/results.go
- openstack/autoscaling/v1/lifecyclehooks/urls.go
Support lifecycle hook callback parameters and methods
```release-note
Support lifecycle hook callback parameters and methods
```
> feat(as): support lifecycle hook callback parameters and methods

- openstack/dms/v2/availablezones/results.go
> fix(dms): fix region id json name

- openstack/apigw/dedicated/v2/plugins/results.go
All time's reference are incorrect.
- 'created_at' -> 'create_time'
- 'updated_at' -> 'update_time'
```release-note
```
> fix(apig/plugin): fix the invalid attribute reference

- openstack/apigw/dedicated/v2/apigroups/results.go
Supports new attributes, the related documentation link is: https://support.huaweicloud.com/intl/en-us/api-apig/ListApiGroupsV2.html
```release-note
1. url domain structure supports new attributes
```
> chore(apig/group): url domain structure supports new attrs

- openstack/dms/v2/kafka/instances/requests.go
Add param `tenant_ips` for kafka instance.
> feat(dms): add param for kafka instance

- openstack/dms/v2/kafka/instances/requests.go
- openstack/dms/v2/kafka/instances/results.go
Support new params and attrs for kafka.
> feat(dms): support new params and attrs for kafka

- openstack/smn/v2/subscriptions/results.go
fix FilterPolicy.StringEquals attr format
```
fix FilterPolicy.StringEquals attr format
```
> fix(smn): fix FilterPolicy.StringEquals attr format

- openstack/sfs_turbo/v1/shares/results.go
SFS Turbo resource support backup_id field
```release-note
```
> feat(sfs): SFS Turbo support backup_id field

- openstack/cce/v3/nodepools/requests.go
- openstack/cce/v3/nodepools/results.go
> feat(cce): add some new parameters in node pool

- openstack/taurusdb/v3/configurations/requests.go
- openstack/taurusdb/v3/configurations/results.go
- openstack/taurusdb/v3/configurations/urls.go
- openstack/taurusdb/v3/instances/requests.go
- openstack/taurusdb/v3/instances/urls.go
- openstack/taurusdb/v3/parameters/requests.go
- openstack/taurusdb/v3/parameters/results.go
- openstack/taurusdb/v3/parameters/urls.go
gaussdb mysql instance support new methods
```release-note
```
> feat(GaussDB): gaussdb mysql instance support new methods

- openstack/taurusdb/v3/instances/requests.go
fix gaussdb mysql instance restart method param
```release-note
```
> fix(Gaussdb): fix gaussdb mysql instance restart method param

- openstack/csms/v1/secrets/requests.go
- openstack/csms/v1/secrets/results.go
The secret resource support new fields.
```release-note
```
> feat(dew): the secret resource support new fields

- openstack/vpcep/v1/endpoints/requests.go
- openstack/vpcep/v1/endpoints/results.go
- openstack/vpcep/v1/endpoints/urls.go
new additions and improvements new sdk to vpcep endpoint sdk
```release-note
```
> chore: new additions and improvements new sdk to vpcep endpoint sdk

- openstack/cce/v3/nodepools/requests.go
- openstack/cce/v3/nodes/results.go
> feat(cce): support enterprise_project_id in node and node pool

- openstack/taurusdb/v3/instances/requests.go
- openstack/taurusdb/v3/instances/urls.go
gaussdb mysql support more methods
```release-note
```
> feat(GaussDBForMySQL): gaussdb mysql support more methods

- openstack/elb/v3/loadbalancers/requests.go
- openstack/elb/v3/loadbalancers/results.go
elb loadbalancer support gateway mode
```release-note
```
> feat(ELB): elb loadbalancer support gateway mode

- openstack/ims/v2/cloudimages/requests.go
Support new parameters for `CreateByOBSOpts` struct
```release-note
Support new parameters for `CreateByOBSOpts` struct
```
> feat(ims): support new parameters for `CreateByOBSOpts` struct

- openstack/cce/v3/clusters/requests.go
- openstack/cce/v3/clusters/results.go
> feat(cce): support LtsReclaimPolicy and ServiceNetwork in cluster

- openstack/cce/v3/nodes/results.go
> feat(cce): add HostnameConfig in node

- openstack/cce/v3/nodes/requests.go
> feat(cce): support hostname_config in node attach

- openstack/cce/v3/nodepools/requests.go
- openstack/cce/v3/nodepools/results.go
> feat(cce): support extensionScaleGroups in node pool

- openstack/vpcep/v1/services/requests.go
The VPC endpoint service resource supports tcp_proxy field.
```release-note
```
> feat(vpcep): the VPC endpoint service resource supports tcp_proxy field

- openstack/vpcep/v1/endpoints/results.go
- openstack/vpcep/v1/services/requests.go
- openstack/vpcep/v1/services/results.go
Tthe VPC endpoint and VPC endpoint service resources support ip_version field.
```release-note
```
> feat(vpcep): the VPC endpoint and VPC endpoint service resources support ip_version field

- openstack/taurusdb/v3/autoscaling/requests.go
- openstack/taurusdb/v3/autoscaling/results.go
- openstack/taurusdb/v3/autoscaling/urls.go
- openstack/taurusdb/v3/backups/requests.go
- openstack/taurusdb/v3/backups/results.go
- openstack/taurusdb/v3/backups/urls.go
gaussdb mysql support new methods auto scaling and encryption
```release-note
```
> feat(GaussDBforMySQL): gaussdb mysql support new methods

- openstack/ecs/v1/flavors/results.go
> feat(ecs): add storageType in Flavor results

- openstack/drs/v3/jobs/requests.go
support setting kafka security config
> feat(drs): support setting kafka security config

- openstack/ecs/v1/cloudservers/results_job.go
- openstack/ecs/v1/cloudservers/results_order.go
> feat(ecs): add ServerIDs in JobResponse and OrderResponse

- openstack/drs/v3/jobs/requests.go
Support new param public ip list.
> feat(drs): support new param public ip list

- openstack/dms/v2/rabbitmq/instances/requests.go
- openstack/dms/v2/rabbitmq/instances/results.go
Support new param and remove required for some params.
> feat(dms): support new param and remove required for some params

- openstack/fgs/v2/function/requests.go
Max async retry attempts supports zero value.
```release-note
1. max async retry attempts supports zero value.
```
> fix(fgs/async): max async retry attempts supports zero value

- openstack/taurusdb/v3/instances/requests.go
- openstack/taurusdb/v3/instances/results.go
- openstack/taurusdb/v3/instances/urls.go
gaussdb mysql instance support version
```release-note
```
> feat(GaussDBforMySQL): gaussdb mysql instance support version

- openstack/waf_hw/v1/policies/requests.go
waf policy support new field.
```release-note
```
> feat(WAF): waf policy support new field

- openstack/cdm/v1/link/requests.go
> fix(cdm): fix type of input value

- openstack/ecs/v1/cloudservers/requests.go
> feat(ecs): support tags in ListOpts

- openstack/geminidb/v3/instances/requests.go
gausdb redis instance support az detail
```release-note
```
> feat(GaussDBforNoSQL): gausdb redis instance support az detail

- openstack/taurusdb/v3/instances/requests.go
- openstack/taurusdb/v3/instances/results.go
- openstack/taurusdb/v3/instances/urls.go
gaussdb mysql instance support slow log show original switch
```release-note
```
> feat(GaussDBforMySQL): gaussdb mysql instance support slow log show original switch

- openstack/vpcep/v1/services/requests.go
- openstack/vpcep/v1/services/results.go
The VPC endpoint service resource supports new fields.
```release-note
```
> feat(vpcep): the VPC endpoint service resource supports new fields

- openstack/drs/v3/jobs/requests.go
- openstack/drs/v3/jobs/results.go
> feat(drs): add new param for job

- openstack/drs/v3/jobs/results.go
> feat(drs): add new attributes for job

- errors.go
- provider_client.go
Supports new default error code for 502 bad gateway.
```release-note
1. error code supports 502 for bad gateway.
```
> feat(errors): error code supports 502 for bad gateway

- openstack/dms/v2/kafka/instances/results.go
support port protocols for kafka instance
> feat(dms): support port protocols for kafka instance

- openstack/waf_hw/v1/premium_instances/requests.go
Waf dedicated support new field `tags`.
This field is not editable and has no corresponding value.
```release-note
```
> feat(WAF): waf dedicated support new field

- openstack/cce/v3/nodes/results.go
> refactor(cce): remove useless attributes in cce node

- openstack/evs/v2/cloudvolumes/requests.go
- openstack/evs/v2/cloudvolumes/urls.go
evs support new sdk to update volume type
```release-note
```
> feat(evs): evs support new sdk to update volume type

- openstack/apigw/dedicated/v2/responses/requests.go
New parameters headers is supported for rule structure.
```release-note
1. rule supports new headers parameter.
```
> feat(apig/response): rule supports new headers parameter

- openstack/apigw/dedicated/v2/channels/requests.go
- openstack/apigw/dedicated/v2/channels/results.go
New parameters are support:
- vpc_channel_type (that used to instead the old parameter: type)
- reference_vpc_channel_id
```release-note
1. add new parameters support.
```
> feat(apig/channel): add new params support

- openstack/apigw/dedicated/v2/apis/requests.go
- openstack/apigw/dedicated/v2/apis/results.go
New parameters are supported for API request body:
- content_type
- is_send_fg_body_base64
```release-note
1. new parameters are supported for request body
```
> feat(apig/api): new parameters are supported for request body

- openstack/networking/v1/vpcs/requests.go
- openstack/networking/v1/vpcs/results.go
vpc support new param enhanced_local_route
```release-note
```
> feat(VPC): vpc support new param enhanced_local_route

- openstack/opengauss/v3/instances/results.go
gaussdb opengauss support mysql compatibility
```release-note
```
> feat(GaussDB): gaussdb opengauss support mysql compatibility

- openstack/cce/v3/nodes/results.go
> feat(cce): add Iops and Throughput in VolumeSpec of node and node pool

- openstack/dns/v2/zones/requests.go
- openstack/dns/v2/zones/results.go
The private zone supports new attribute `proxy_pattern`.
```release-note
add new attribute 'proxy_pattern'.
```
> feat(dns): the private zone supports new attribute 'proxy_pattern'

- openstack/nat/v2/snats/results.go
The SNAT rule resource supports new attributes.
```release-note
```
> feat(nat): the SNAT rule resource supports new attributes

- openstack/cloudeyeservice/v2/alarmrule/requests.go
make the policies field optional
```release-note
```
> feat(ces): make the policies field optional

- openstack/elb/v3/listeners/requests.go
- openstack/elb/v3/listeners/results.go
- openstack/elb/v3/loadbalancers/results.go
add params to elb loadbalancer and listener
```release-note
```
> feat(ELB): add params to elb loadbalancer and listener

- openstack/autoscaling/v1/configurations/results.go
The AS configuration support new attribute.
```release-note
```
> feat(as): the AS configuration support new attribute

- openstack/mrs/v2/clusters/requests.go
The cluster and its nodes support `is_auto_renew` parameter.
```release-note
```
> feat(mrs/cluster): the cluster and its nodes support auto renew

- OWNERS
fix owners
```release-note
```
> feat: fix owners

- openstack/cce/v3/clusters/requests.go
- openstack/cce/v3/clusters/results.go
cce cluster support timezone
```release-note
cce cluster support timezone
```
> feat(CCE): cce cluster support timezone

- openstack/vpcep/v1/endpoints/results.go
> refactor(vpcep): remove Error in Endpoint struct

- openstack/networking/v1/vpcs/requests.go
> feat(vpc): add BlockServiceEndpointStates in CreateOpts

- errors.go
- provider_client.go
New kinds of 409 error supported.
```release-note
New kinds of 409 error supported.
```
> feat(error): new kinds of 409 error supported

- openstack/vpcep/v1/endpoints/requests.go
- openstack/vpcep/v1/endpoints/results.go
> refactor(vpcep): refactor PolicyStatement to interface{}

- openstack/dms/v2/kafka/instances/requests.go
- openstack/dms/v2/kafka/instances/urls.go
add new creation API and support the `port_protocol` parameter.
```release-note
```
> chore(kafka): add new creation api and support the port_protocol parameter

- openstack/cce/v3/nodepools/requests.go
> feat(cce/nodepool): add IgnoreInitialNodeCount in UpdateSpec

- openstack/ecs/v1/cloudservers/requests.go
- openstack/ecs/v1/cloudservers/results.go
> feat(ecs): support EnclaveOptions in compute instance

- openstack/servicestage/v2/environments/requests.go
- openstack/servicestage/v2/environments/results.go
> feat(servicestage): add new parameter
